import assert from "node:assert/strict";
import { mkdir, mkdtemp, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import path from "node:path";
import test from "node:test";
import { verifyCLI } from "../verify-cli.mjs";

const MATCHING_RUN = [
  "func Run() generated.Command {",
  "  for _, command := range generated.Commands {",
  "    if len(command.Path) > 0 { return command }",
  "  }",
  "  return generated.Command{}",
  "}",
].join("\n");

const BASE_FILES = {
  "go.mod": "module example.test\n\ngo 1.27.0\n",
  "cmd/vsk-labs/main.go": [
    "package main",
    'import "example.test/internal/cli"',
    "func main() { cli.Run() }",
    "",
  ].join("\n"),
  "internal/cli/run.go": [
    "package cli",
    'import "example.test/internal/generated"',
    MATCHING_RUN,
    "",
  ].join("\n"),
  "internal/generated/contracts_gen.go": [
    "// Code generated by fixture; DO NOT EDIT.",
    "package generated",
    'const RegistrySchemaVersion = "1.0.0"',
    "type Command struct { Path []string }",
    "var Commands = []Command{}",
    "",
  ].join("\n"),
};

async function fixtureRepo(t, files = {}) {
  const root = await mkdtemp(path.join(tmpdir(), "vegastack-cli-fixture-"));
  t.after(() => rm(root, { recursive: true, force: true }));
  const contents = { ...BASE_FILES, ...files };
  await Promise.all(
    Object.entries(contents).map(async ([relative, content]) => {
      const destination = path.join(root, relative);
      await mkdir(path.dirname(destination), { recursive: true });
      await writeFile(destination, content, "utf8");
    }),
  );
  return root;
}

test("the CLI verifier accepts one generated-registry consumer", async (t) => {
  const root = await fixtureRepo(t);
  const result = await verifyCLI(root, { crossBuild: false });
  assert.deepEqual(result, { status: "pass", codes: [], targetsBuilt: [] });
});

test("inventory control commands cannot reach SQLite, shells, providers, arbitrary HTTP, server paths, or domain engines", async (t) => {
  const root = await fixtureRepo(t, {
    "internal/cli/run.go": [
      "package cli",
      "import (",
      '  _ "database/sql"',
      '  _ "net/http"',
      '  _ "os/exec"',
      '  _ "example.test/internal/cloudflare"',
      '  _ "example.test/internal/google"',
      '  _ "example.test/internal/inventory"',
      '  "example.test/internal/generated"',
      ")",
      'const ServerPath = "/var/lib/private/control.db"',
      MATCHING_RUN,
      "",
    ].join("\n"),
    "internal/cloudflare/client.go": "package cloudflare\n",
    "internal/google/client.go": "package google\n",
    "internal/inventory/service.go": "package inventory\n",
  });
  const result = await verifyCLI(root, { crossBuild: false });
  assert.deepEqual(result.codes, [
    "CLI_CONTROL_SQLITE_ACCESS",
    "CLI_CONTROL_SHELL_DISPATCH",
    "CLI_CONTROL_GOOGLE_ACCESS",
    "CLI_CONTROL_PROVIDER_ACCESS",
    "CLI_CONTROL_ARBITRARY_HTTP",
    "CLI_CONTROL_SERVER_PATH",
    "CLI_INVENTORY_DIRECT_DOMAIN",
  ]);
});

test("the CLI verifier permits HTTP only as ordinary code in the named local service packages", async (t) => {
  const root = await fixtureRepo(t, {
    "internal/cli/run.go": [
      "package cli",
      'import ("example.test/internal/generated"; _ "example.test/internal/server")',
      MATCHING_RUN,
      "",
    ].join("\n"),
    "internal/server/service.go": [
      "package server",
      'import ("net/http"; _ "example.test/internal/localapi")',
      "func Serve(writer http.ResponseWriter, request *http.Request) {}",
      "",
    ].join("\n"),
    "internal/localapi/client.go": [
      "package localapi",
      'import "net/http"',
      "func Client() *http.Client { return &http.Client{} }",
      "",
    ].join("\n"),
  });
  const result = await verifyCLI(root, { crossBuild: false });
  assert.deepEqual(result, { status: "pass", codes: [], targetsBuilt: [] });
});

test("the CLI verifier requires the shipped dependency closure to consume generated contracts", async (t) => {
  const root = await fixtureRepo(t, {
    "cmd/vsk-labs/main.go": "package main\nfunc main() {}\n",
  });
  const result = await verifyCLI(root, { crossBuild: false });
  assert.deepEqual(result.codes, ["CLI_GENERATED_OWNERSHIP"]);
});

test("the CLI verifier requires the exact generated Commands symbol, not another generated symbol", async (t) => {
  const root = await fixtureRepo(t, {
    "internal/cli/run.go": [
      "package cli",
      'import "example.test/internal/generated"',
      "func Run() { _ = generated.RegistrySchemaVersion }",
      "",
    ].join("\n"),
  });
  const result = await verifyCLI(root, { crossBuild: false });
  assert.deepEqual(result.codes, ["CLI_GENERATED_OWNERSHIP"]);
});

test("the CLI verifier does not accept a blank generated import as ownership", async (t) => {
  const root = await fixtureRepo(t, {
    "internal/cli/run.go": [
      "package cli",
      'import _ "example.test/internal/generated"',
      "func Run() {}",
      "",
    ].join("\n"),
  });
  const result = await verifyCLI(root, { crossBuild: false });
  assert.deepEqual(result.codes, ["CLI_GENERATED_OWNERSHIP"]);
});

test("the CLI verifier does not accept a discarded Commands selector as ownership", async (t) => {
  const root = await fixtureRepo(t, {
    "internal/cli/run.go": [
      "package cli",
      'import "example.test/internal/generated"',
      "func Run() {",
      "  _ = generated.Commands",
      '  switch "help" { case "help": return }',
      "}",
      "",
    ].join("\n"),
  });
  const result = await verifyCLI(root, { crossBuild: false });
  assert.deepEqual(result.codes, ["CLI_GENERATED_OWNERSHIP"]);
});

test("the CLI verifier rejects an empty generated range followed by literal switch dispatch", async (t) => {
  const root = await fixtureRepo(t, {
    "internal/cli/run.go": [
      "package cli",
      'import "example.test/internal/generated"',
      "func Run() {",
      "  for range generated.Commands {}",
      '  switch "help" { case "help": return }',
      "}",
      "",
    ].join("\n"),
  });
  const result = await verifyCLI(root, { crossBuild: false });
  assert.deepEqual(result.codes, ["CLI_GENERATED_OWNERSHIP"]);
});

test("the CLI verifier rejects a ranged command that does not drive a returned match", async (t) => {
  const root = await fixtureRepo(t, {
    "internal/cli/run.go": [
      "package cli",
      'import "example.test/internal/generated"',
      "func Run() {",
      "  for _, command := range generated.Commands {",
      "    if len(command.Path) > 0 { continue }",
      "  }",
      '  switch "help" { case "help": return }',
      "}",
      "",
    ].join("\n"),
  });
  const result = await verifyCLI(root, { crossBuild: false });
  assert.deepEqual(result.codes, ["CLI_GENERATED_OWNERSHIP"]);
});

test("the CLI verifier rejects a generated field named Commands as an ownership impostor", async (t) => {
  const root = await fixtureRepo(t, {
    "internal/generated/contracts_gen.go": [
      "// Code generated by fixture; DO NOT EDIT.",
      "package generated",
      "type Command struct{}",
      "var Commands = []Command{}",
      "type Bait struct { Commands []Command }",
      "",
    ].join("\n"),
    "internal/cli/run.go": [
      "package cli",
      'import "example.test/internal/generated"',
      "func Run() { value := generated.Bait{}; _ = value.Commands }",
      "",
    ].join("\n"),
  });
  const result = await verifyCLI(root, { crossBuild: false });
  assert.deepEqual(result.codes, ["CLI_GENERATED_OWNERSHIP"]);
});

test("the CLI verifier rejects a second executable", async (t) => {
  const root = await fixtureRepo(t, {
    "cmd/helper/main.go": "package main\nfunc main() {}\n",
  });
  const result = await verifyCLI(root, { crossBuild: false });
  assert.equal(result.status, "fail");
  assert.deepEqual(result.codes, ["CLI_EXECUTABLE_COUNT"]);
});

test("the CLI verifier rejects differently named slice and map command registries", async (t) => {
  const root = await fixtureRepo(t, {
    "internal/cli/run.go": [
      "package cli",
      'import "example.test/internal/generated"',
      "var sidecar = []generated.Command{}",
      "var routes = map[string]generated.Command{}",
      "var stale []generated.Command",
      "func copiedRegistry() { copied := make([]generated.Command, 0); _ = copied }",
      MATCHING_RUN,
      "",
    ].join("\n"),
  });
  const result = await verifyCLI(root, { crossBuild: false });
  assert.deepEqual(result.codes, ["CLI_HANDWRITTEN_REGISTRY"]);
});

test("the CLI verifier rejects custom route types and function-valued dispatch", async (t) => {
  const root = await fixtureRepo(t, {
    "internal/cli/run.go": [
      "package cli",
      'import "example.test/internal/generated"',
      "type Route struct { Path string; Handle func() }",
      "var routeList = []Route{}",
      "var routeMap = map[string]Route{}",
      "var dispatch = map[string]func(){}",
      MATCHING_RUN,
      "",
    ].join("\n"),
  });
  const result = await verifyCLI(root, { crossBuild: false });
  assert.deepEqual(result.codes, ["CLI_HANDWRITTEN_REGISTRY"]);
});

test("the CLI verifier rejects an alias collection of generated commands", async (t) => {
  const root = await fixtureRepo(t, {
    "internal/cli/run.go": [
      "package cli",
      'import "example.test/internal/generated"',
      "type Alias = generated.Command",
      "var stale = []Alias{}",
      MATCHING_RUN,
      "",
    ].join("\n"),
  });
  const result = await verifyCLI(root, { crossBuild: false });
  assert.deepEqual(result.codes, ["CLI_HANDWRITTEN_REGISTRY"]);
});

test("the CLI verifier rejects a locally defined command-copy collection", async (t) => {
  const root = await fixtureRepo(t, {
    "internal/cli/run.go": [
      "package cli",
      'import "example.test/internal/generated"',
      "type LocalCommand generated.Command",
      "var stale = []LocalCommand{}",
      MATCHING_RUN,
      "",
    ].join("\n"),
  });
  const result = await verifyCLI(root, { crossBuild: false });
  assert.deepEqual(result.codes, ["CLI_HANDWRITTEN_REGISTRY"]);
});

test("the CLI verifier rejects a pointer-wrapped alias collection", async (t) => {
  const root = await fixtureRepo(t, {
    "internal/cli/run.go": [
      "package cli",
      'import "example.test/internal/generated"',
      "type Alias = *generated.Command",
      "var stale = []Alias{}",
      MATCHING_RUN,
      "",
    ].join("\n"),
  });
  const result = await verifyCLI(root, { crossBuild: false });
  assert.deepEqual(result.codes, ["CLI_HANDWRITTEN_REGISTRY"]);
});

test("the CLI verifier rejects a pointer-wrapped local command type", async (t) => {
  const root = await fixtureRepo(t, {
    "internal/cli/run.go": [
      "package cli",
      'import "example.test/internal/generated"',
      "type LocalCommand *generated.Command",
      "var stale = []LocalCommand{}",
      MATCHING_RUN,
      "",
    ].join("\n"),
  });
  const result = await verifyCLI(root, { crossBuild: false });
  assert.deepEqual(result.codes, ["CLI_HANDWRITTEN_REGISTRY"]);
});

test("the CLI verifier rejects string-handler route records used by switch dispatch", async (t) => {
  const root = await fixtureRepo(t, {
    "internal/cli/run.go": [
      "package cli",
      'import "example.test/internal/generated"',
      "type Route struct { Path string; HandlerID string }",
      'var routes = map[string]Route{"help": {Path: "help", HandlerID: "show-help"}}',
      "func Run() generated.Command {",
      "  for _, command := range generated.Commands {",
      "    if len(command.Path) > 0 { return command }",
      "  }",
      '  route := routes["help"]',
      '  switch route.HandlerID { case "show-help": return generated.Command{} }',
      "  return generated.Command{}",
      "}",
      "",
    ].join("\n"),
  });
  const result = await verifyCLI(root, { crossBuild: false });
  assert.deepEqual(result.codes, ["CLI_HANDWRITTEN_REGISTRY"]);
});

test("the CLI verifier accepts ordinary non-dispatch maps and slices", async (t) => {
  const root = await fixtureRepo(t, {
    "internal/cli/run.go": [
      "package cli",
      'import "example.test/internal/generated"',
      "type Record struct { Name string; Count int }",
      'var names = []string{"help"}',
      'var counts = map[string]int{"help": 1}',
      'var records = []Record{{Name: "help", Count: 1}}',
      'var recordsByName = map[string]Record{"first": {Name: "first", Count: 1}}',
      "var indexedCallbacks = map[int]func(){1: func() {}}",
      MATCHING_RUN,
      "",
    ].join("\n"),
  });
  const result = await verifyCLI(root, { crossBuild: false });
  assert.deepEqual(result, { status: "pass", codes: [], targetsBuilt: [] });
});

test("the CLI verifier scans imported in-module packages outside the old fixed directories", async (t) => {
  const root = await fixtureRepo(t, {
    "internal/cli/run.go": [
      "package cli",
      "import (",
      '  "example.test/internal/escape"',
      '  "example.test/internal/generated"',
      ")",
      "func init() { escape.Run() }",
      MATCHING_RUN,
      "",
    ].join("\n"),
    "internal/escape/escape.go": [
      "package escape",
      "import (",
      '  "database/sql"',
      '  "os/exec"',
      '  "example.test/internal/generated"',
      ")",
      "var alternateRoutes = map[string]generated.Command{}",
      'func Run() { _ = sql.ErrNoRows; _ = exec.Command("sh", "-c", "status") }',
      "",
    ].join("\n"),
  });
  const result = await verifyCLI(root, { crossBuild: false });
  assert.deepEqual(result.codes, [
    "CLI_HANDWRITTEN_REGISTRY",
    "CLI_SQLITE_ACCESS",
    "CLI_SHELL_DISPATCH",
  ]);
});

test("raw SQLite imports are allowed only in internal/store", async (t) => {
  const allowed = await fixtureRepo(t, {
    "internal/store/store.go": [
      "package store",
      'import "database/sql"',
      "var _ *sql.DB",
      "",
    ].join("\n"),
  });
  assert.deepEqual((await verifyCLI(allowed, { crossBuild: false })).codes, []);

  const denied = await fixtureRepo(t, {
    "internal/store/store.go": "package store\n",
    "internal/api/rogue.go": [
      "package api",
      'import "database/sql"',
      "var _ *sql.DB",
      "",
    ].join("\n"),
  });
  assert.deepEqual((await verifyCLI(denied, { crossBuild: false })).codes, [
    "CLI_SQLITE_ACCESS",
  ]);
});

test("the recovery artifact package cannot become a second SQLite owner", async (t) => {
  const root = await fixtureRepo(t, {
    "internal/cli/run.go": [
      "package cli",
      'import ("example.test/internal/backup"; "example.test/internal/generated")',
      "func init() { backup.Build() }",
      MATCHING_RUN,
      "",
    ].join("\n"),
    "internal/backup/service.go": [
      "package backup",
      'import "database/sql"',
      "func Build() { _ = sql.ErrNoRows }",
      "",
    ].join("\n"),
  });
  assert.deepEqual((await verifyCLI(root, { crossBuild: false })).codes, [
    "CLI_SQLITE_ACCESS",
  ]);
});

test("offline release code rejects network and artifact execution", async (t) => {
  const root = await fixtureRepo(t, {
    "internal/cli/run.go": [
      "package cli",
      "import (",
      '  "example.test/internal/generated"',
      '  _ "example.test/internal/release"',
      ")",
      MATCHING_RUN,
      "",
    ].join("\n"),
    "internal/release/unsafe.go": [
      "package release",
      'import ("net/http"; "os/exec")',
      "var _ = http.Get",
      "var _ = exec.Command",
      "",
    ].join("\n"),
  });
  const result = await verifyCLI(root, { crossBuild: false });
  assert.deepEqual(result.codes, [
    "CLI_RELEASE_NETWORK_ACCESS",
    "CLI_RELEASE_ARTIFACT_EXECUTION",
  ]);
});

const SIGSTORE_STUB_FILES = {
  "sigstore-stub/go.mod": "module github.com/sigstore/sigstore-go\n\ngo 1.27.0\n",
  "sigstore-stub/pkg/bundle/bundle.go": [
    "package bundle",
    "type Bundle struct{}",
    "func LoadJSONFromPath(string) (*Bundle, error) { return nil, nil }",
    "func (*Bundle) UnmarshalJSON([]byte) error { return nil }",
    "",
  ].join("\n"),
  "sigstore-stub/pkg/root/root.go": [
    "package root",
    "type TrustedRoot struct{}",
    "func FetchTrustedRoot() (*TrustedRoot, error) { return nil, nil }",
    "func NewTrustedRootFromJSON([]byte) (*TrustedRoot, error) { return nil, nil }",
    "",
  ].join("\n"),
  "sigstore-stub/pkg/tuf/tuf.go": "package tuf\ntype Client struct{}\n",
  "sigstore-stub/pkg/verify/verify.go": [
    "package verify",
    "type Option struct{}",
    "type Identity struct{}",
    "func WithoutArtifactUnsafe() Option { return Option{} }",
    "func NewShortCertificateIdentity(string, string, string, string) (Identity, error) { return Identity{}, nil }",
    "",
  ].join("\n"),
};

function sigstoreFixtureFiles(releaseSource) {
  return {
    ...SIGSTORE_STUB_FILES,
    "go.mod": [
      "module example.test",
      "",
      "go 1.27.0",
      "",
      "require github.com/sigstore/sigstore-go v1.3.0",
      "replace github.com/sigstore/sigstore-go => ./sigstore-stub",
      "",
    ].join("\n"),
    "internal/cli/run.go": [
      "package cli",
      "import (",
      '  "example.test/internal/generated"',
      '  _ "example.test/internal/release"',
      ")",
      MATCHING_RUN,
      "",
    ].join("\n"),
    "internal/release/release.go": releaseSource,
  };
}

test("offline release code rejects TUF fetches, path loaders, unsafe artifacts, and regex identity", async (t) => {
  const root = await fixtureRepo(t, sigstoreFixtureFiles([
    "package release",
    "import (",
    '  "github.com/sigstore/sigstore-go/pkg/bundle"',
    '  "github.com/sigstore/sigstore-go/pkg/root"',
    '  _ "github.com/sigstore/sigstore-go/pkg/tuf"',
    '  "github.com/sigstore/sigstore-go/pkg/verify"',
    ")",
    "func unsafe() {",
    "  _, _ = root.FetchTrustedRoot()",
    '  _, _ = bundle.LoadJSONFromPath("bundle.json")',
    "  _ = verify.WithoutArtifactUnsafe()",
    '  _, _ = verify.NewShortCertificateIdentity("issuer", ".*", "identity", "")',
    "}",
    "",
  ].join("\n")));
  const result = await verifyCLI(root, { crossBuild: false });
  assert.deepEqual(result.codes, [
    "CLI_RELEASE_NETWORK_ACCESS",
    "CLI_RELEASE_ARTIFACT_EXECUTION",
  ]);
});

test("offline release code accepts local bytes and exact non-regex identity", async (t) => {
  const root = await fixtureRepo(t, sigstoreFixtureFiles([
    "package release",
    "import (",
    '  "github.com/sigstore/sigstore-go/pkg/bundle"',
    '  "github.com/sigstore/sigstore-go/pkg/root"',
    '  "github.com/sigstore/sigstore-go/pkg/verify"',
    ")",
    "func safe() {",
    "  var value bundle.Bundle",
    "  _ = value.UnmarshalJSON([]byte(`{}`))",
    "  _, _ = root.NewTrustedRootFromJSON([]byte(`{}`))",
    '  _, _ = verify.NewShortCertificateIdentity("issuer", "", "identity", "")',
    "}",
    "",
  ].join("\n")));
  const result = await verifyCLI(root, { crossBuild: false });
  assert.deepEqual(result, { status: "pass", codes: [], targetsBuilt: [] });
});

test("production cannot provide export keys or reuse release trust", async (t) => {
  const keyRepo = await fixtureRepo(t, {
    "internal/stateexport/key.go": "package stateexport\nimport \"crypto/ed25519\"\nvar privateKey ed25519.PrivateKey\n",
  });
  assert.deepEqual((await verifyCLI(keyRepo, { crossBuild: false })).codes, [
    "CLI_STATE_EXPORT_TRUST",
  ]);

  const releaseRepo = await fixtureRepo(t, {
    "internal/stateexport/release.go": "package stateexport\nimport _ \"example.test/internal/release\"\n",
    "internal/release/policy.go": "package release\ntype ReleaseTrustPolicy struct{}\n",
  });
  assert.deepEqual((await verifyCLI(releaseRepo, { crossBuild: false })).codes, [
    "CLI_STATE_EXPORT_RELEASE_COUPLING",
  ]);
});

test("production cannot compose concrete export signer and verifier implementations", async (t) => {
  const root = await fixtureRepo(t, {
    "internal/stateexport/types.go": "package stateexport\ntype Config struct { Signer any; Verifier any }\n",
    "internal/server/export.go": "package server\nimport se \"example.test/internal/stateexport\"\nvar configured = se.Config{Signer: struct{}{}, Verifier: struct{}{}}\n",
  });
  assert.deepEqual((await verifyCLI(root, { crossBuild: false })).codes, [
    "CLI_STATE_EXPORT_TRUST",
  ]);
});

test("production cannot assign export trust fields before NewService", async (t) => {
  const root = await fixtureRepo(t, {
    "internal/cli/run.go": [
      "package cli",
      'import ("example.test/internal/generated"; _ "example.test/internal/server")',
      MATCHING_RUN,
      "",
    ].join("\n"),
    "internal/stateexport/types.go": [
      "package stateexport",
      "type Config struct { Signer any; Verifier any }",
      "func NewService(Config) {}",
      "",
    ].join("\n"),
    "internal/server/export.go": [
      "package server",
      'import se "example.test/internal/stateexport"',
      "var adapter = struct{}{}",
      "func wire() {",
      "  cfg := se.Config{}",
      "  cfg.Signer, cfg.Verifier = adapter, adapter",
      "  se.NewService(cfg)",
      "}",
      "",
    ].join("\n"),
  });
  assert.deepEqual((await verifyCLI(root, { crossBuild: false })).codes, [
    "CLI_STATE_EXPORT_TRUST",
  ]);
});

test("production executable closure cannot import asymmetric signing packages", async (t) => {
  const root = await fixtureRepo(t, {
    "internal/cli/run.go": [
      "package cli",
      'import ("example.test/internal/generated"; _ "example.test/internal/exportadapter")',
      MATCHING_RUN,
      "",
    ].join("\n"),
    "internal/exportadapter/sign.go": [
      "package exportadapter",
      'import "crypto/ed25519"',
      "var publicKey ed25519.PublicKey",
      "",
    ].join("\n"),
  });
  assert.deepEqual((await verifyCLI(root, { crossBuild: false })).codes, [
    "CLI_STATE_EXPORT_TRUST",
  ]);
});

test("the CLI verifier scans target-specific dependency closures", async (t) => {
  const root = await fixtureRepo(t, {
    "internal/cli/escape_windows.go": [
      "package cli",
      'import "example.test/internal/escape"',
      "func init() { escape.Run() }",
      "",
    ].join("\n"),
    "internal/escape/escape.go": [
      "package escape",
      "import (",
      '  "database/sql"',
      '  "os/exec"',
      '  "example.test/internal/generated"',
      ")",
      "type Route struct { Path string; Handle func() }",
      "var windowsRoutes = []Route{}",
      'func Run() { _ = sql.ErrNoRows; _ = generated.Commands; _ = exec.Command("cmd.exe", "/C", "status") }',
      "",
    ].join("\n"),
  });
  const result = await verifyCLI(root, { crossBuild: false });
  assert.deepEqual(result.codes, [
    "CLI_HANDWRITTEN_REGISTRY",
    "CLI_SQLITE_ACCESS",
    "CLI_SHELL_DISPATCH",
  ]);
});

test("the CLI verifier type-checks Windows-only standard-library symbols in the Windows target context", async (t) => {
  const root = await fixtureRepo(t, {
    "internal/cli/native_windows.go": [
      "package cli",
      'import "syscall"',
      'var kernel = syscall.NewLazyDLL("kernel32.dll")',
      "",
    ].join("\n"),
  });
  const result = await verifyCLI(root, { crossBuild: false });
  assert.deepEqual(result, { status: "pass", codes: [], targetsBuilt: [] });
});

test("the CLI verifier fails closed when the analyzer reports a mismatched target", async (t) => {
  const root = await fixtureRepo(t);
  let calls = 0;
  const result = await verifyCLI(root, {
    crossBuild: false,
    runAnalyzer: async (_command, args) => {
      calls += 1;
      const goos = args[args.indexOf("--goos") + 1];
      const goarch = args[args.indexOf("--goarch") + 1];
      const target = calls === 3 ? "plan9/amd64" : `${goos}/${goarch}`;
      return {
        stdout: `${JSON.stringify({
          generatedCommandsReference: true,
          generatedEndpointsReference: true,
          handwrittenRegistry: false,
          controlArbitraryHTTP: false,
          controlGoogleAccess: false,
          controlProviderAccess: false,
          controlSQLiteAccess: false,
          controlServerPath: false,
          controlShellDispatch: false,
          inventoryDirectDomain: false,
          releaseArtifactExecution: false,
          releaseNetworkAccess: false,
          sqliteAccess: false,
          shellDispatch: false,
          stateExportReleaseCoupling: false,
          stateExportTrust: false,
          targetsAnalyzed: [target],
        })}\n`,
      };
    },
  });
  assert.equal(calls, 5);
  assert.deepEqual(result, { status: "fail", codes: ["CLI_CROSS_BUILD"], targetsBuilt: [] });
});

test("the CLI verifier fails closed on missing or nonboolean analyzer fields", async (t) => {
  const root = await fixtureRepo(t);
  const malformedResults = [
    {
      generatedCommandsReference: true,
      targetsAnalyzed: ["linux/amd64"],
    },
    {
      generatedCommandsReference: "true",
      handwrittenRegistry: false,
      releaseArtifactExecution: false,
      releaseNetworkAccess: false,
      sqliteAccess: false,
      shellDispatch: false,
      stateExportReleaseCoupling: false,
      stateExportTrust: false,
      targetsAnalyzed: ["linux/amd64"],
    },
  ];
  for (const malformed of malformedResults) {
    const result = await verifyCLI(root, {
      crossBuild: false,
      runAnalyzer: async () => ({ stdout: `${JSON.stringify(malformed)}\n` }),
    });
    assert.deepEqual(result, {
      status: "fail",
      codes: ["CLI_GENERATED_OWNERSHIP"],
      targetsBuilt: [],
    });
  }
});

test("the CLI verifier requires cmd/vsk-labs as the sole executable", async (t) => {
  const root = await fixtureRepo(t, {
    "cmd/vsk-labs/main.go": "package helper\nfunc Run() {}\n",
    "cmd/helper/main.go": "package main\nfunc main() {}\n",
  });
  const result = await verifyCLI(root, { crossBuild: false });
  assert.deepEqual(result.codes, ["CLI_EXECUTABLE_COUNT", "CLI_GENERATED_OWNERSHIP"]);
});

test("the cross-build compiles the executable and store for five independent targets", async (t) => {
  const root = await fixtureRepo(t);
  const calls = [];
  const removed = [];
  const outputDirectory = path.join(tmpdir(), "injected-cli-build-success");
  const result = await verifyCLI(root, {
    createBuildDirectory: async () => outputDirectory,
    removeBuildDirectory: async (...args) => removed.push(args),
    runBuild: async (command, args, options) => calls.push({ command, args, options }),
  });

  const expectedTargets = [
    ["linux", "amd64"],
    ["linux", "arm64"],
    ["darwin", "amd64"],
    ["darwin", "arm64"],
    ["windows", "amd64"],
  ];
  assert.deepEqual(
    calls.map(({ options }) => [options.env.GOOS, options.env.GOARCH]),
    expectedTargets.flatMap((target) => [target, target]),
  );
  assert.equal(new Set(calls.map(({ args }) => args[2])).size, expectedTargets.length * 2);
  assert.deepEqual(
    calls.filter(({ args }) => args[3] === "./cmd/vsk-labs").map(({ args }) => path.basename(args[2])),
    [
      "vsk-labs-linux-amd64",
      "vsk-labs-linux-arm64",
      "vsk-labs-darwin-amd64",
      "vsk-labs-darwin-arm64",
      "vsk-labs-windows-amd64.exe",
    ],
  );
  assert.deepEqual(
    calls.filter(({ args }) => args[3] === "./internal/store").map(({ args }) => path.basename(args[2])),
    [
      "store-linux-amd64.a",
      "store-linux-arm64.a",
      "store-darwin-amd64.a",
      "store-darwin-arm64.a",
      "store-windows-amd64.a",
    ],
  );
  assert.deepEqual(result, {
    status: "pass",
    codes: [],
    targetsBuilt: expectedTargets.map(([goos, goarch]) => `${goos}/${goarch}`),
  });
  assert.deepEqual(removed, [[outputDirectory, { recursive: true, force: true }]]);
});

test("the cross-build cleans its isolated output after a mid-matrix failure", async (t) => {
  const root = await fixtureRepo(t);
  const outputs = [];
  const removed = [];
  const outputDirectory = path.join(tmpdir(), "injected-cli-build-failure");
  const result = await verifyCLI(root, {
    createBuildDirectory: async () => outputDirectory,
    removeBuildDirectory: async (...args) => removed.push(args),
    runBuild: async (_command, args) => {
      outputs.push(args[2]);
      if (outputs.length === 3) throw new Error("injected cross-build failure");
    },
  });

  assert.equal(outputs.length, 3);
  assert.equal(new Set(outputs).size, 3);
  assert.deepEqual(result, { status: "fail", codes: ["CLI_CROSS_BUILD"], targetsBuilt: [] });
  assert.deepEqual(removed, [[outputDirectory, { recursive: true, force: true }]]);
});
