import assert from "node:assert/strict";
import { mkdir, mkdtemp, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import path from "node:path";
import test from "node:test";
import { verifyCLI } from "../verify-cli.mjs";

const BASE_FILES = {
  "go.mod": "module example.test\n\ngo 1.27.0\n",
  "cmd/vsk-labs/main.go": [
    "package main",
    'import "example.test/internal/cli"',
    "func main() { cli.Run() }",
    "",
  ].join("\n"),
  "internal/cli/run.go": [
    "package cli",
    'import "example.test/internal/generated"',
    "func Run() { _ = generated.Commands }",
    "",
  ].join("\n"),
  "internal/generated/contracts_gen.go": [
    "// Code generated by fixture; DO NOT EDIT.",
    "package generated",
    'const RegistrySchemaVersion = "1.0.0"',
    "type Command struct{}",
    "var Commands = []Command{}",
    "",
  ].join("\n"),
};

async function fixtureRepo(t, files = {}) {
  const root = await mkdtemp(path.join(tmpdir(), "vegastack-cli-fixture-"));
  t.after(() => rm(root, { recursive: true, force: true }));
  const contents = { ...BASE_FILES, ...files };
  await Promise.all(
    Object.entries(contents).map(async ([relative, content]) => {
      const destination = path.join(root, relative);
      await mkdir(path.dirname(destination), { recursive: true });
      await writeFile(destination, content, "utf8");
    }),
  );
  return root;
}

test("the CLI verifier accepts one generated-registry consumer", async (t) => {
  const root = await fixtureRepo(t);
  const result = await verifyCLI(root, { crossBuild: false });
  assert.deepEqual(result, { status: "pass", codes: [], targetsBuilt: [] });
});

test("the CLI verifier requires the shipped dependency closure to consume generated contracts", async (t) => {
  const root = await fixtureRepo(t, {
    "cmd/vsk-labs/main.go": "package main\nfunc main() {}\n",
  });
  const result = await verifyCLI(root, { crossBuild: false });
  assert.deepEqual(result.codes, ["CLI_GENERATED_OWNERSHIP"]);
});

test("the CLI verifier requires the exact generated Commands symbol, not another generated symbol", async (t) => {
  const root = await fixtureRepo(t, {
    "internal/cli/run.go": [
      "package cli",
      'import "example.test/internal/generated"',
      "func Run() { _ = generated.RegistrySchemaVersion }",
      "",
    ].join("\n"),
  });
  const result = await verifyCLI(root, { crossBuild: false });
  assert.deepEqual(result.codes, ["CLI_GENERATED_OWNERSHIP"]);
});

test("the CLI verifier does not accept a blank generated import as ownership", async (t) => {
  const root = await fixtureRepo(t, {
    "internal/cli/run.go": [
      "package cli",
      'import _ "example.test/internal/generated"',
      "func Run() {}",
      "",
    ].join("\n"),
  });
  const result = await verifyCLI(root, { crossBuild: false });
  assert.deepEqual(result.codes, ["CLI_GENERATED_OWNERSHIP"]);
});

test("the CLI verifier rejects a second executable", async (t) => {
  const root = await fixtureRepo(t, {
    "cmd/helper/main.go": "package main\nfunc main() {}\n",
  });
  const result = await verifyCLI(root, { crossBuild: false });
  assert.equal(result.status, "fail");
  assert.deepEqual(result.codes, ["CLI_EXECUTABLE_COUNT"]);
});

test("the CLI verifier rejects differently named slice and map command registries", async (t) => {
  const root = await fixtureRepo(t, {
    "internal/cli/run.go": [
      "package cli",
      'import "example.test/internal/generated"',
      "var sidecar = []generated.Command{}",
      "var routes = map[string]generated.Command{}",
      "var stale []generated.Command",
      "func Run() { copied := make([]generated.Command, 0); _ = generated.Commands; _ = sidecar; _ = routes; _ = stale; _ = copied }",
      "",
    ].join("\n"),
  });
  const result = await verifyCLI(root, { crossBuild: false });
  assert.deepEqual(result.codes, ["CLI_HANDWRITTEN_REGISTRY"]);
});

test("the CLI verifier rejects custom route types and function-valued dispatch", async (t) => {
  const root = await fixtureRepo(t, {
    "internal/cli/run.go": [
      "package cli",
      'import "example.test/internal/generated"',
      "type Route struct { Path string; Handle func() }",
      "var routeList = []Route{}",
      "var routeMap = map[string]Route{}",
      "var dispatch = map[string]func(){}",
      "func Run() { _ = generated.Commands; _ = routeList; _ = routeMap; _ = dispatch }",
      "",
    ].join("\n"),
  });
  const result = await verifyCLI(root, { crossBuild: false });
  assert.deepEqual(result.codes, ["CLI_HANDWRITTEN_REGISTRY"]);
});

test("the CLI verifier accepts ordinary non-dispatch maps and slices", async (t) => {
  const root = await fixtureRepo(t, {
    "internal/cli/run.go": [
      "package cli",
      'import "example.test/internal/generated"',
      "type Record struct { Name string; Count int }",
      'var names = []string{"help"}',
      'var counts = map[string]int{"help": 1}',
      'var records = []Record{{Name: "help", Count: 1}}',
      "var indexedCallbacks = map[int]func(){1: func() {}}",
      "func Run() { _ = generated.Commands; _ = names; _ = counts; _ = records; _ = indexedCallbacks }",
      "",
    ].join("\n"),
  });
  const result = await verifyCLI(root, { crossBuild: false });
  assert.deepEqual(result, { status: "pass", codes: [], targetsBuilt: [] });
});

test("the CLI verifier scans imported in-module packages outside the old fixed directories", async (t) => {
  const root = await fixtureRepo(t, {
    "internal/cli/run.go": [
      "package cli",
      "import (",
      '  "example.test/internal/escape"',
      '  "example.test/internal/generated"',
      ")",
      "func Run() { _ = generated.Commands; escape.Run() }",
      "",
    ].join("\n"),
    "internal/escape/escape.go": [
      "package escape",
      "import (",
      '  "database/sql"',
      '  "os/exec"',
      '  "example.test/internal/generated"',
      ")",
      "var alternateRoutes = map[string]generated.Command{}",
      'func Run() { _ = sql.ErrNoRows; _ = exec.Command("sh", "-c", "status") }',
      "",
    ].join("\n"),
  });
  const result = await verifyCLI(root, { crossBuild: false });
  assert.deepEqual(result.codes, [
    "CLI_HANDWRITTEN_REGISTRY",
    "CLI_SQLITE_ACCESS",
    "CLI_SHELL_DISPATCH",
  ]);
});

test("the CLI verifier scans target-specific dependency closures", async (t) => {
  const root = await fixtureRepo(t, {
    "internal/cli/escape_windows.go": [
      "package cli",
      'import "example.test/internal/escape"',
      "func init() { escape.Run() }",
      "",
    ].join("\n"),
    "internal/escape/escape.go": [
      "package escape",
      "import (",
      '  "database/sql"',
      '  "os/exec"',
      '  "example.test/internal/generated"',
      ")",
      "type Route struct { Path string; Handle func() }",
      "var windowsRoutes = []Route{}",
      'func Run() { _ = sql.ErrNoRows; _ = generated.Commands; _ = exec.Command("cmd.exe", "/C", "status") }',
      "",
    ].join("\n"),
  });
  const result = await verifyCLI(root, { crossBuild: false });
  assert.deepEqual(result.codes, [
    "CLI_HANDWRITTEN_REGISTRY",
    "CLI_SQLITE_ACCESS",
    "CLI_SHELL_DISPATCH",
  ]);
});

test("the CLI verifier requires cmd/vsk-labs as the sole executable", async (t) => {
  const root = await fixtureRepo(t, {
    "cmd/vsk-labs/main.go": "package helper\nfunc Run() {}\n",
    "cmd/helper/main.go": "package main\nfunc main() {}\n",
  });
  const result = await verifyCLI(root, { crossBuild: false });
  assert.deepEqual(result.codes, ["CLI_EXECUTABLE_COUNT", "CLI_GENERATED_OWNERSHIP"]);
});

test("the cross-build uses the independently expected five targets and unique outputs", async (t) => {
  const root = await fixtureRepo(t);
  const calls = [];
  const removed = [];
  const outputDirectory = path.join(tmpdir(), "injected-cli-build-success");
  const result = await verifyCLI(root, {
    createBuildDirectory: async () => outputDirectory,
    removeBuildDirectory: async (...args) => removed.push(args),
    runBuild: async (command, args, options) => calls.push({ command, args, options }),
  });

  const expectedTargets = [
    ["linux", "amd64"],
    ["linux", "arm64"],
    ["darwin", "amd64"],
    ["darwin", "arm64"],
    ["windows", "amd64"],
  ];
  assert.deepEqual(
    calls.map(({ options }) => [options.env.GOOS, options.env.GOARCH]),
    expectedTargets,
  );
  assert.equal(new Set(calls.map(({ args }) => args[2])).size, expectedTargets.length);
  assert.deepEqual(
    calls.map(({ args }) => path.basename(args[2])),
    [
      "vsk-labs-linux-amd64",
      "vsk-labs-linux-arm64",
      "vsk-labs-darwin-amd64",
      "vsk-labs-darwin-arm64",
      "vsk-labs-windows-amd64.exe",
    ],
  );
  assert.deepEqual(result, {
    status: "pass",
    codes: [],
    targetsBuilt: expectedTargets.map(([goos, goarch]) => `${goos}/${goarch}`),
  });
  assert.deepEqual(removed, [[outputDirectory, { recursive: true, force: true }]]);
});

test("the cross-build cleans its isolated output after a mid-matrix failure", async (t) => {
  const root = await fixtureRepo(t);
  const outputs = [];
  const removed = [];
  const outputDirectory = path.join(tmpdir(), "injected-cli-build-failure");
  const result = await verifyCLI(root, {
    createBuildDirectory: async () => outputDirectory,
    removeBuildDirectory: async (...args) => removed.push(args),
    runBuild: async (_command, args) => {
      outputs.push(args[2]);
      if (outputs.length === 3) throw new Error("injected cross-build failure");
    },
  });

  assert.equal(outputs.length, 3);
  assert.equal(new Set(outputs).size, 3);
  assert.deepEqual(result, { status: "fail", codes: ["CLI_CROSS_BUILD"], targetsBuilt: [] });
  assert.deepEqual(removed, [[outputDirectory, { recursive: true, force: true }]]);
});
