import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import path from "node:path";
import test from "node:test";
import { fileURLToPath } from "node:url";

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "../..");

test("the public lane checks generated contracts without writing them", async () => {
  const packageJson = JSON.parse(await readFile(path.join(ROOT, "package.json"), "utf8"));
  assert.equal(
    packageJson.scripts["generate:contracts"],
    "go run ./tooling/generate-contracts --write",
  );
  assert.equal(
    packageJson.scripts["check:contracts"],
    "go run ./tooling/generate-contracts --check",
  );

  const check = await readFile(path.join(ROOT, "tooling/lib/check-plan.mjs"), "utf8");
  assert.match(
    check,
    /commandStep\("generated contracts", "go", "go", \["run", "\.\/tooling\/generate-contracts", "--check"\]\)/,
  );
  assert.doesNotMatch(check, /generate-contracts", "--write"/);
});

test("development docs expose the approved Phase 1 generated-contract boundary", async () => {
  const phase = await readFile(
    path.join(ROOT, "docs/development/phases/01-portable-executable-and-generated-contracts.md"),
    "utf8",
  );
  const contributing = await readFile(path.join(ROOT, "CONTRIBUTING.md"), "utf8");
  const phaseZero = await readFile(
    path.join(ROOT, "docs/development/phases/00-development-foundation.md"),
    "utf8",
  );
  assert.match(phase, /Issue #24.*Issue #25/is);
  assert.match(phase, /available.*planned/is);
  assert.match(phase, /G-018.*remain(?:s)? open/is);
  assert.match(contributing, /pnpm generate:contracts/);
  assert.match(contributing, /never edit.*generated/is);
  assert.match(phaseZero, /Issue #22.*PR #23.*9b57392/is);
  assert.doesNotMatch(phaseZero, /correction candidate/i);
});

test("Phase 4 validators and browser decoders remain generator-owned", async () => {
  const generator = await readFile(path.join(ROOT, "internal/contractgen/generate.go"), "utf8");
  const generatedValidator = await readFile(path.join(ROOT, "internal/generated/contracts_validate_gen.go"), "utf8");
  const browser = await readFile(path.join(ROOT, "web/generated/read-api.ts"), "utf8");
  const endpoints = JSON.parse(await readFile(path.join(ROOT, "schemas/v1/endpoint-registry.json"), "utf8"));

  assert.match(generator, /renderGoValidators/);
  assert.match(generatedValidator, /Code generated by go run \.\/tooling\/generate-contracts --write; DO NOT EDIT\./);
  assert.match(browser, /decodePhase4Contract/);
  assert.equal(
    endpoints.endpoints
      .filter(
        (endpoint) =>
          endpoint.ownerPhase === "4" &&
          ![
            "api.v1.declarations.revise",
            "api.v1.declarations.get",
            "api.v1.plans.create",
            "api.v1.plans.get",
            "api.v1.plans.acknowledgements.create",
            "api.v1.plans.acknowledgements.get",
            "api.v1.plans.execute",
            "api.v1.runs.get",
            "api.v1.runs.cancel",
            "api.v1.runs.resume",
          ].includes(endpoint.id),
      )
      .every((endpoint) => endpoint.availability === "planned"),
    true,
  );
});
