package main

import (
	"slices"
	"strings"
)

// Issue225 additive exact source closures. Historical Issue223 seals remain unchanged.
var debianAccessSourceSeals = map[string]hostActionSourceSeal{
	"cmd/vsk-labs|access_rollback_linux.go,host_action_linux.go,main.go,native_probe_linux.go":                                             {imports: []string{"context", "crypto/rand", "encoding/hex", "github.com/vegastack/vegastack-labs/internal/adapter/nativecredential", "github.com/vegastack/vegastack-labs/internal/backup", "github.com/vegastack/vegastack-labs/internal/cli", "github.com/vegastack/vegastack-labs/internal/clientfile", "github.com/vegastack/vegastack-labs/internal/debianaccess", "github.com/vegastack/vegastack-labs/internal/hostaction", "github.com/vegastack/vegastack-labs/internal/release", "github.com/vegastack/vegastack-labs/internal/result", "github.com/vegastack/vegastack-labs/internal/server", "os", "os/signal", "strconv", "syscall", "time"}, digest: "9a48e6f5f4d97d6be19cf3ff982a5f2106581b5879de4d9bea69ea8b082e0c4e"},
	"cmd/vsk-labs|access_rollback_unsupported.go,host_action_unsupported.go,main.go,native_probe_unsupported.go":                           {imports: []string{"context", "crypto/rand", "encoding/hex", "github.com/vegastack/vegastack-labs/internal/backup", "github.com/vegastack/vegastack-labs/internal/cli", "github.com/vegastack/vegastack-labs/internal/clientfile", "github.com/vegastack/vegastack-labs/internal/release", "github.com/vegastack/vegastack-labs/internal/result", "github.com/vegastack/vegastack-labs/internal/server", "os", "os/signal", "syscall"}, digest: "3a1e120ce55e2414783b81cd3a25e776ab1a2e121e4aec8ed42543d7404edf47"},
	"internal/adapter/hostaction|access_render.go,access_render_lock.go,access_render_unix.go,access_sequence.go,adapter.go,ssh.go":        {imports: []string{"bufio", "bytes", "context", "encoding/base64", "encoding/json", "github.com/vegastack/vegastack-labs/ansible", "github.com/vegastack/vegastack-labs/internal/adapter", "github.com/vegastack/vegastack-labs/internal/credentialref", "github.com/vegastack/vegastack-labs/internal/debianaccess", "github.com/vegastack/vegastack-labs/internal/failure", "github.com/vegastack/vegastack-labs/internal/generated", "github.com/vegastack/vegastack-labs/internal/hostaction", "github.com/vegastack/vegastack-labs/internal/strictjson", "golang.org/x/crypto/ssh", "io", "io/fs", "net", "os", "os/exec", "path/filepath", "strconv", "strings", "sync", "syscall", "time"}, digest: "bd981e20cf7451fed5ff6d684ac6279303d3dbd2f2cb7486c2289310d6278178"},
	"internal/adapter/hostaction|access_render.go,access_render_lock.go,access_render_unsupported.go,access_sequence.go,adapter.go,ssh.go": {imports: []string{"bufio", "bytes", "context", "encoding/base64", "encoding/json", "github.com/vegastack/vegastack-labs/ansible", "github.com/vegastack/vegastack-labs/internal/adapter", "github.com/vegastack/vegastack-labs/internal/credentialref", "github.com/vegastack/vegastack-labs/internal/debianaccess", "github.com/vegastack/vegastack-labs/internal/failure", "github.com/vegastack/vegastack-labs/internal/generated", "github.com/vegastack/vegastack-labs/internal/hostaction", "github.com/vegastack/vegastack-labs/internal/strictjson", "golang.org/x/crypto/ssh", "io", "io/fs", "net", "os", "os/exec", "path/filepath", "strconv", "strings", "sync", "time"}, digest: "4c6ad4c74f7d852148e6573f53233ea542a1c5cb436de4fe3b57856d2bd2f993"},
	"internal/debianaccess|configuration.go,destinations_unix.go,draft.go,handler.go,input.go,observations_unix.go,preparation.go,probe.go,probe_socket.go,probe_udp.go,rollback.go,rollback_unix.go,runner.go,runtime_unix.go,sequence.go,sequence_policy.go,source_probe.go,source_probe_linux.go,sudo_policy.go,sudo_policy_unix.go,timer.go,timer_unix.go":       {imports: []string{"bytes", "context", "crypto/ed25519", "crypto/rand", "crypto/sha256", "encoding/hex", "encoding/json", "errors", "fmt", "github.com/vegastack/vegastack-labs/internal/credentialref", "github.com/vegastack/vegastack-labs/internal/generated", "github.com/vegastack/vegastack-labs/internal/hostaction", "github.com/vegastack/vegastack-labs/internal/strictjson", "golang.org/x/crypto/ssh", "golang.org/x/sys/unix", "io", "net", "net/netip", "os", "os/exec", "path", "path/filepath", "regexp", "runtime", "sort", "strconv", "strings", "sync/atomic", "syscall", "time"}, digest: "54595fb07cdf28c204383bbe5b1446f9dc521b20e7df26acaeb588680346c418"},
	"internal/debianaccess|configuration.go,destinations_unix.go,draft.go,handler.go,input.go,observations_unix.go,preparation.go,probe.go,probe_socket.go,probe_udp.go,rollback.go,rollback_unix.go,runner.go,runtime_unix.go,sequence.go,sequence_policy.go,source_probe.go,source_probe_unsupported.go,sudo_policy.go,sudo_policy_unix.go,timer.go,timer_unix.go": {imports: []string{"bytes", "context", "crypto/ed25519", "crypto/rand", "crypto/sha256", "encoding/hex", "encoding/json", "errors", "fmt", "github.com/vegastack/vegastack-labs/internal/credentialref", "github.com/vegastack/vegastack-labs/internal/generated", "github.com/vegastack/vegastack-labs/internal/hostaction", "github.com/vegastack/vegastack-labs/internal/strictjson", "golang.org/x/crypto/ssh", "golang.org/x/sys/unix", "io", "net", "net/netip", "os", "os/exec", "path", "regexp", "runtime", "sort", "strconv", "strings", "sync/atomic", "syscall", "time"}, digest: "0dcff6943fdd02a78051b3d4ea6c48a5d4e8ed6f309456902a654b150db78dec"},
	"internal/debianaccess|configuration.go,draft.go,handler.go,input.go,preparation.go,probe.go,probe_socket.go,probe_udp.go,rollback.go,runner.go,sequence.go,sequence_policy.go,source_probe.go,source_probe_unsupported.go,sudo_policy.go,timer.go":                                                                                                              {imports: []string{"bytes", "context", "crypto/ed25519", "crypto/rand", "crypto/sha256", "encoding/hex", "encoding/json", "errors", "fmt", "github.com/vegastack/vegastack-labs/internal/credentialref", "github.com/vegastack/vegastack-labs/internal/generated", "github.com/vegastack/vegastack-labs/internal/hostaction", "github.com/vegastack/vegastack-labs/internal/strictjson", "golang.org/x/crypto/ssh", "io", "net", "net/netip", "os", "os/exec", "path", "regexp", "sort", "strconv", "strings", "sync/atomic", "syscall", "time"}, digest: "5a27b2c0f4becc53805562b92b65baa812d53721717b8239b4e9a6d0a52cae55"},
	"internal/hostaction|bundle.go,once.go,pipe_other.go,platform_unsupported.go,request.go,result.go":       {imports: []string{"bufio", "context", "crypto/ed25519", "crypto/sha256", "encoding/base64", "encoding/hex", "encoding/json", "github.com/vegastack/vegastack-labs/internal/failure", "github.com/vegastack/vegastack-labs/internal/generated", "github.com/vegastack/vegastack-labs/internal/strictjson", "io", "os", "time"}, digest: "8238485b161c60e600b1f06f4ea4bbae9892a8e6011b071ab7e5fb095e7a2249"},
	"internal/hostaction|bundle.go,once.go,pipe_unix.go,policy_unix.go,receipt_unix.go,request.go,result.go": {imports: []string{"bufio", "bytes", "context", "crypto/ed25519", "crypto/sha256", "encoding/base64", "encoding/hex", "encoding/json", "github.com/vegastack/vegastack-labs/internal/failure", "github.com/vegastack/vegastack-labs/internal/generated", "github.com/vegastack/vegastack-labs/internal/strictjson", "golang.org/x/sys/unix", "io", "os", "path/filepath", "regexp", "strings", "sync", "time"}, digest: "3675a399e7f9b279f5ce77ec81ca8448a5ce154f3ab1a1a049663d2cd0be3ee2"},
}

func reviewedDebianAccessPackage(c checkedSourcePackage, module, relative string) bool {
	if c.listed.ImportPath != module+"/"+relative || len(c.listed.CgoFiles) != 0 {
		return false
	}
	names := append([]string(nil), c.listed.GoFiles...)
	slices.Sort(names)
	seal, ok := debianAccessSourceSeals[relative+"|"+strings.Join(names, ",")]
	if !ok {
		return false
	}
	imports := append([]string(nil), c.listed.Imports...)
	slices.Sort(imports)
	expected := append([]string(nil), seal.imports...)
	for i, v := range expected {
		expected[i] = strings.Replace(v, "github.com/vegastack/vegastack-labs/", module+"/", 1)
	}
	slices.Sort(expected)
	return slices.Equal(imports, expected) && digestSourceFiles(c.listed.Dir, names) == seal.digest
}
