package main

import (
	"slices"
	"strings"
)

// Issue226 additive exact source closures. Historical Issue223/225 seals remain unchanged.
var debianBaselineSourceSeals = map[string]hostActionSourceSeal{
	"cmd/vsk-labs|access_rollback_linux.go,host_action_linux.go,main.go,native_probe_linux.go":                                                                                    {imports: []string{"context", "crypto/rand", "encoding/hex", "github.com/vegastack/vegastack-labs/internal/adapter/nativecredential", "github.com/vegastack/vegastack-labs/internal/backup", "github.com/vegastack/vegastack-labs/internal/cli", "github.com/vegastack/vegastack-labs/internal/clientfile", "github.com/vegastack/vegastack-labs/internal/debianaccess", "github.com/vegastack/vegastack-labs/internal/debianbaseline", "github.com/vegastack/vegastack-labs/internal/hostaction", "github.com/vegastack/vegastack-labs/internal/release", "github.com/vegastack/vegastack-labs/internal/result", "github.com/vegastack/vegastack-labs/internal/server", "os", "os/signal", "strconv", "syscall", "time"}, digest: "1d1ba29bc740ae0651ef9bc0e8fc01bae600061ea3445a0ff2c046a0e99184a5"},
	"cmd/vsk-labs|access_rollback_unsupported.go,host_action_unsupported.go,main.go,native_probe_unsupported.go":                                                                  {imports: []string{"context", "crypto/rand", "encoding/hex", "github.com/vegastack/vegastack-labs/internal/backup", "github.com/vegastack/vegastack-labs/internal/cli", "github.com/vegastack/vegastack-labs/internal/clientfile", "github.com/vegastack/vegastack-labs/internal/release", "github.com/vegastack/vegastack-labs/internal/result", "github.com/vegastack/vegastack-labs/internal/server", "os", "os/signal", "syscall"}, digest: "3a1e120ce55e2414783b81cd3a25e776ab1a2e121e4aec8ed42543d7404edf47"},
	"internal/adapter/hostaction|access_render.go,access_render_lock.go,access_render_unix.go,access_sequence.go,adapter.go,baseline_render.go,profile_renderer.go,ssh.go":        {imports: []string{"bufio", "bytes", "context", "encoding/base64", "encoding/json", "github.com/vegastack/vegastack-labs/ansible", "github.com/vegastack/vegastack-labs/internal/adapter", "github.com/vegastack/vegastack-labs/internal/credentialref", "github.com/vegastack/vegastack-labs/internal/debianaccess", "github.com/vegastack/vegastack-labs/internal/debianbaseline", "github.com/vegastack/vegastack-labs/internal/failure", "github.com/vegastack/vegastack-labs/internal/generated", "github.com/vegastack/vegastack-labs/internal/hostaction", "github.com/vegastack/vegastack-labs/internal/strictjson", "golang.org/x/crypto/ssh", "io", "io/fs", "net", "os", "os/exec", "path/filepath", "strconv", "strings", "sync", "syscall", "time"}, digest: "d46dc43e17c970a251c29c35cbe6ee3f1611ebe4f4c9df790e0fc89e5970fa52"},
	"internal/adapter/hostaction|access_render.go,access_render_lock.go,access_render_unsupported.go,access_sequence.go,adapter.go,baseline_render.go,profile_renderer.go,ssh.go": {imports: []string{"bufio", "bytes", "context", "encoding/base64", "encoding/json", "github.com/vegastack/vegastack-labs/ansible", "github.com/vegastack/vegastack-labs/internal/adapter", "github.com/vegastack/vegastack-labs/internal/credentialref", "github.com/vegastack/vegastack-labs/internal/debianaccess", "github.com/vegastack/vegastack-labs/internal/debianbaseline", "github.com/vegastack/vegastack-labs/internal/failure", "github.com/vegastack/vegastack-labs/internal/generated", "github.com/vegastack/vegastack-labs/internal/hostaction", "github.com/vegastack/vegastack-labs/internal/strictjson", "golang.org/x/crypto/ssh", "io", "io/fs", "net", "os", "os/exec", "path/filepath", "strconv", "strings", "sync", "time"}, digest: "9c4c8f7731b970d2006369a1109d72d403f8d086d3043d72c5406750e8ad9fc5"},
	"internal/debianaccess|baseline.go,baseline_profiles_unix.go,baseline_unix.go,configuration.go,destinations_unix.go,draft.go,fail2ban.go,handler.go,input.go,observations_unix.go,preparation.go,probe.go,probe_socket.go,probe_udp.go,rollback.go,rollback_unix.go,runner.go,runtime_unix.go,sequence.go,sequence_policy.go,source_probe.go,source_probe_linux.go,sudo_policy.go,sudo_policy_unix.go,timer.go,timer_unix.go":       {imports: []string{"bytes", "context", "crypto/ed25519", "crypto/rand", "crypto/sha256", "encoding/hex", "encoding/json", "errors", "fmt", "github.com/vegastack/vegastack-labs/internal/credentialref", "github.com/vegastack/vegastack-labs/internal/generated", "github.com/vegastack/vegastack-labs/internal/hostaction", "github.com/vegastack/vegastack-labs/internal/strictjson", "golang.org/x/crypto/ssh", "golang.org/x/sys/unix", "io", "net", "net/netip", "os", "os/exec", "path", "path/filepath", "regexp", "runtime", "sort", "strconv", "strings", "sync/atomic", "syscall", "time"}, digest: "f8c9efbf840987b846bda9bd29f5e767ed5555e7f0c0dd57ee6d8bf086402be9"},
	"internal/debianaccess|baseline.go,baseline_profiles_unix.go,baseline_unix.go,configuration.go,destinations_unix.go,draft.go,fail2ban.go,handler.go,input.go,observations_unix.go,preparation.go,probe.go,probe_socket.go,probe_udp.go,rollback.go,rollback_unix.go,runner.go,runtime_unix.go,sequence.go,sequence_policy.go,source_probe.go,source_probe_unsupported.go,sudo_policy.go,sudo_policy_unix.go,timer.go,timer_unix.go": {imports: []string{"bytes", "context", "crypto/ed25519", "crypto/rand", "crypto/sha256", "encoding/hex", "encoding/json", "errors", "fmt", "github.com/vegastack/vegastack-labs/internal/credentialref", "github.com/vegastack/vegastack-labs/internal/generated", "github.com/vegastack/vegastack-labs/internal/hostaction", "github.com/vegastack/vegastack-labs/internal/strictjson", "golang.org/x/crypto/ssh", "golang.org/x/sys/unix", "io", "net", "net/netip", "os", "os/exec", "path", "regexp", "runtime", "sort", "strconv", "strings", "sync/atomic", "syscall", "time"}, digest: "d57899aa8f492a1846e7731313bde50f6f22ff1013b732a03c778fd3861bd8d1"},
	"internal/debianaccess|baseline.go,configuration.go,draft.go,fail2ban.go,handler.go,input.go,preparation.go,probe.go,probe_socket.go,probe_udp.go,rollback.go,runner.go,sequence.go,sequence_policy.go,source_probe.go,source_probe_unsupported.go,sudo_policy.go,timer.go":                                                                                                                                                         {imports: []string{"bytes", "context", "crypto/ed25519", "crypto/rand", "crypto/sha256", "encoding/hex", "encoding/json", "errors", "fmt", "github.com/vegastack/vegastack-labs/internal/credentialref", "github.com/vegastack/vegastack-labs/internal/generated", "github.com/vegastack/vegastack-labs/internal/hostaction", "github.com/vegastack/vegastack-labs/internal/strictjson", "golang.org/x/crypto/ssh", "io", "net", "net/netip", "os", "os/exec", "path", "regexp", "sort", "strconv", "strings", "sync/atomic", "syscall", "time"}, digest: "20096bc11f62cc0484b50e9d13159024577f9859007d79bedefd3a5c079b28e9"},
	"internal/debianbaseline|aide.go,apparmor.go,apply_unix.go,apt_unix.go,audit.go,collect.go,fail2ban.go,handler.go,health.go,input.go,native_unix.go,policy.go,reader.go,time_unix.go,volume_files_unix.go,volume_linux.go,volume_mapping.go,volume_metadata.go,volume_recovery_linux.go,volume_recovery_unix.go":                                                                                                                    {imports: []string{"bytes", "context", "crypto/sha256", "encoding/binary", "encoding/hex", "encoding/json", "errors", "fmt", "github.com/vegastack/vegastack-labs/internal/debianaccess", "github.com/vegastack/vegastack-labs/internal/generated", "github.com/vegastack/vegastack-labs/internal/hostaction", "github.com/vegastack/vegastack-labs/internal/strictjson", "golang.org/x/sys/unix", "io", "math", "net/netip", "os", "os/exec", "path", "path/filepath", "reflect", "regexp", "runtime", "slices", "sort", "strconv", "strings", "syscall", "time"}, digest: "4fc1d7aea78fb93d37a4bdbe2cea7d119e5506f981a52c64c8bf867b75a3870c"},
	"internal/debianbaseline|aide.go,apparmor.go,apply_unix.go,apt_unix.go,audit.go,collect.go,fail2ban.go,handler.go,health.go,input.go,native_unix.go,policy.go,reader.go,time_unix.go,volume_files_unix.go,volume_mapping.go,volume_metadata.go,volume_recovery_unix.go,volume_unsupported.go":                                                                                                                                       {imports: []string{"bytes", "context", "crypto/sha256", "encoding/binary", "encoding/hex", "encoding/json", "errors", "fmt", "github.com/vegastack/vegastack-labs/internal/debianaccess", "github.com/vegastack/vegastack-labs/internal/generated", "github.com/vegastack/vegastack-labs/internal/hostaction", "github.com/vegastack/vegastack-labs/internal/strictjson", "golang.org/x/sys/unix", "io", "math", "net/netip", "os", "os/exec", "path", "reflect", "regexp", "runtime", "slices", "sort", "strconv", "strings", "syscall", "time"}, digest: "c5e54022028fbd0191a0d407a484e43930c7fe2d886ccde47e19d4bf61dedea6"},
	"internal/debianbaseline|aide.go,apparmor.go,audit.go,collect.go,fail2ban.go,handler.go,health.go,input.go,native_unsupported.go,policy.go,reader.go,volume_mapping.go,volume_metadata.go,volume_unsupported.go":                                                                                                                                                                                                                    {imports: []string{"bytes", "context", "crypto/sha256", "encoding/binary", "encoding/hex", "encoding/json", "errors", "fmt", "github.com/vegastack/vegastack-labs/internal/debianaccess", "github.com/vegastack/vegastack-labs/internal/generated", "github.com/vegastack/vegastack-labs/internal/hostaction", "github.com/vegastack/vegastack-labs/internal/strictjson", "math", "net/netip", "path", "reflect", "regexp", "slices", "sort", "strconv", "strings", "time"}, digest: "1ed74dde6ea1484ef9d051d86356f3f00a89f77ae60e2c50de685a98c41973a2"},
	"internal/hostaction|bundle.go,once.go,pipe_other.go,platform_unsupported.go,request.go,result.go":       {imports: []string{"bufio", "context", "crypto/ed25519", "crypto/sha256", "encoding/base64", "encoding/hex", "encoding/json", "github.com/vegastack/vegastack-labs/internal/failure", "github.com/vegastack/vegastack-labs/internal/generated", "github.com/vegastack/vegastack-labs/internal/strictjson", "io", "os", "time"}, digest: "8238485b161c60e600b1f06f4ea4bbae9892a8e6011b071ab7e5fb095e7a2249"},
	"internal/hostaction|bundle.go,once.go,pipe_unix.go,policy_unix.go,receipt_unix.go,request.go,result.go": {imports: []string{"bufio", "bytes", "context", "crypto/ed25519", "crypto/sha256", "encoding/base64", "encoding/hex", "encoding/json", "github.com/vegastack/vegastack-labs/internal/failure", "github.com/vegastack/vegastack-labs/internal/generated", "github.com/vegastack/vegastack-labs/internal/strictjson", "golang.org/x/sys/unix", "io", "os", "path/filepath", "regexp", "strings", "sync", "time"}, digest: "3675a399e7f9b279f5ce77ec81ca8448a5ce154f3ab1a1a049663d2cd0be3ee2"},
}

func reviewedDebianBaselinePackage(c checkedSourcePackage, module, relative string) bool {
	if c.listed.ImportPath != module+"/"+relative || len(c.listed.CgoFiles) != 0 {
		return false
	}
	names := append([]string(nil), c.listed.GoFiles...)
	slices.Sort(names)
	seal, ok := debianBaselineSourceSeals[relative+"|"+strings.Join(names, ",")]
	if !ok {
		return false
	}
	imports := append([]string(nil), c.listed.Imports...)
	slices.Sort(imports)
	expected := append([]string(nil), seal.imports...)
	for i, v := range expected {
		expected[i] = strings.Replace(v, "github.com/vegastack/vegastack-labs/", module+"/", 1)
	}
	slices.Sort(expected)
	return slices.Equal(imports, expected) && digestSourceFiles(c.listed.Dir, names) == seal.digest
}
