package main

import (
	"slices"
	"strings"
)

// Issue230 additive exact source closures. Historical source seals remain unchanged.
const reviewedLinuxRoleSetupGrantDigest = "0ddefc9cffcb9cedad5689697e17d727e7e69037b1314be250f207af3c71423b"

var linuxRoleSourceSeals = map[string]hostActionSourceSeal{
	"cmd/vsk-labs|access_rollback_linux.go,host_action_linux.go,main.go,native_probe_linux.go":                                                                                                                                                     {imports: []string{"context", "crypto/rand", "encoding/hex", "github.com/vegastack/vegastack-labs/internal/adapter/nativecredential", "github.com/vegastack/vegastack-labs/internal/backup", "github.com/vegastack/vegastack-labs/internal/cli", "github.com/vegastack/vegastack-labs/internal/clientfile", "github.com/vegastack/vegastack-labs/internal/debianaccess", "github.com/vegastack/vegastack-labs/internal/debianbaseline", "github.com/vegastack/vegastack-labs/internal/hostaction", "github.com/vegastack/vegastack-labs/internal/linuxrole", "github.com/vegastack/vegastack-labs/internal/release", "github.com/vegastack/vegastack-labs/internal/result", "github.com/vegastack/vegastack-labs/internal/server", "os", "os/signal", "strconv", "syscall", "time"}, digest: "bd692360f739ddf3fea18eadcccdda635f9dc69ab9da02cbdd7e93f28a023fdb"},
	"cmd/vsk-labs|access_rollback_unsupported.go,host_action_unsupported.go,main.go,native_probe_unsupported.go":                                                                                                                                   {imports: []string{"context", "crypto/rand", "encoding/hex", "github.com/vegastack/vegastack-labs/internal/backup", "github.com/vegastack/vegastack-labs/internal/cli", "github.com/vegastack/vegastack-labs/internal/clientfile", "github.com/vegastack/vegastack-labs/internal/release", "github.com/vegastack/vegastack-labs/internal/result", "github.com/vegastack/vegastack-labs/internal/server", "os", "os/signal", "syscall"}, digest: "3a1e120ce55e2414783b81cd3a25e776ab1a2e121e4aec8ed42543d7404edf47"},
	"internal/adapter/hostaction|access_render.go,access_render_lock.go,access_render_unix.go,access_sequence.go,adapter.go,baseline_render.go,linux_role_render.go,profile_renderer.go,ssh.go":                                                    {imports: []string{"bufio", "bytes", "context", "encoding/base64", "encoding/json", "github.com/vegastack/vegastack-labs/ansible", "github.com/vegastack/vegastack-labs/internal/adapter", "github.com/vegastack/vegastack-labs/internal/credentialref", "github.com/vegastack/vegastack-labs/internal/debianaccess", "github.com/vegastack/vegastack-labs/internal/debianbaseline", "github.com/vegastack/vegastack-labs/internal/failure", "github.com/vegastack/vegastack-labs/internal/generated", "github.com/vegastack/vegastack-labs/internal/hostaction", "github.com/vegastack/vegastack-labs/internal/linuxrole", "github.com/vegastack/vegastack-labs/internal/strictjson", "golang.org/x/crypto/ssh", "io", "io/fs", "net", "os", "os/exec", "path/filepath", "strconv", "strings", "sync", "syscall", "time"}, digest: "e2da54964aae1755c61ca7a78d6c2e24068a5c9e610a99e48e48b849e29391ea"},
	"internal/adapter/hostaction|access_render.go,access_render_lock.go,access_render_unsupported.go,access_sequence.go,adapter.go,baseline_render.go,linux_role_render.go,profile_renderer.go,ssh.go":                                             {imports: []string{"bufio", "bytes", "context", "encoding/base64", "encoding/json", "github.com/vegastack/vegastack-labs/ansible", "github.com/vegastack/vegastack-labs/internal/adapter", "github.com/vegastack/vegastack-labs/internal/credentialref", "github.com/vegastack/vegastack-labs/internal/debianaccess", "github.com/vegastack/vegastack-labs/internal/debianbaseline", "github.com/vegastack/vegastack-labs/internal/failure", "github.com/vegastack/vegastack-labs/internal/generated", "github.com/vegastack/vegastack-labs/internal/hostaction", "github.com/vegastack/vegastack-labs/internal/linuxrole", "github.com/vegastack/vegastack-labs/internal/strictjson", "golang.org/x/crypto/ssh", "io", "io/fs", "net", "os", "os/exec", "path/filepath", "strconv", "strings", "sync", "time"}, digest: "cb1e8540d09ebcb5e68a0c951934b7d3e987dee510bb9c0040a38b5042721d69"},
	"internal/linuxrole|boot_linux.go,collect_linux.go,control_handoff_linux.go,control_install.go,handler.go,input.go,isolation_linux.go,prepare.go,runtime_linux.go":                                                                             {imports: []string{"bytes", "context", "crypto/sha256", "encoding/hex", "encoding/json", "errors", "fmt", "github.com/vegastack/vegastack-labs/internal/debianaccess", "github.com/vegastack/vegastack-labs/internal/debianbaseline", "github.com/vegastack/vegastack-labs/internal/generated", "github.com/vegastack/vegastack-labs/internal/hostaction", "github.com/vegastack/vegastack-labs/internal/strictjson", "golang.org/x/sys/unix", "io", "net", "net/http", "os", "os/exec", "path", "reflect", "regexp", "runtime", "slices", "sort", "strconv", "strings", "syscall", "time"}, digest: "22edb7ecf727586a4a92ee0a150c12e361b113070fdef7557cc95b5dbc71d057"},
	"internal/linuxrole|control_install.go,handler.go,input.go,prepare.go,runtime_unsupported.go":                                                                                                                                                  {imports: []string{"context", "crypto/sha256", "encoding/hex", "encoding/json", "errors", "fmt", "github.com/vegastack/vegastack-labs/internal/debianaccess", "github.com/vegastack/vegastack-labs/internal/generated", "github.com/vegastack/vegastack-labs/internal/hostaction", "github.com/vegastack/vegastack-labs/internal/strictjson", "reflect", "slices", "strings", "time"}, digest: "ecf5b2bdbfc3c6d6971a359f1f02b8e449f8fecaeaecc48212c7646136506890"},
	"internal/localapi|audit_client.go,backup_client.go,client.go,credential_client.go,credential_lifecycle_client.go,database_client.go,gates_client.go,hosts_client.go,listener.go,listener_linux.go,restore_client.go,schedule_client.go":       {imports: []string{"bytes", "context", "crypto/sha256", "encoding/hex", "encoding/json", "errors", "github.com/vegastack/vegastack-labs/internal/credentialref", "github.com/vegastack/vegastack-labs/internal/failure", "github.com/vegastack/vegastack-labs/internal/generated", "github.com/vegastack/vegastack-labs/internal/localtransport", "github.com/vegastack/vegastack-labs/internal/principal", "github.com/vegastack/vegastack-labs/internal/result", "github.com/vegastack/vegastack-labs/internal/runprotocol", "github.com/vegastack/vegastack-labs/internal/serverconfig", "github.com/vegastack/vegastack-labs/internal/sshtransport", "golang.org/x/sys/unix", "io", "mime", "net", "os", "path/filepath", "runtime", "strconv", "strings", "sync", "time"}, digest: "291833adbf46f9de5954ebde056a384f878f262cef19b475f05e52bbf9c839ee"},
	"internal/localapi|audit_client.go,backup_client.go,client.go,credential_client.go,credential_lifecycle_client.go,database_client.go,gates_client.go,hosts_client.go,listener.go,listener_unsupported.go,restore_client.go,schedule_client.go": {imports: []string{"bytes", "context", "crypto/sha256", "encoding/hex", "encoding/json", "errors", "github.com/vegastack/vegastack-labs/internal/credentialref", "github.com/vegastack/vegastack-labs/internal/failure", "github.com/vegastack/vegastack-labs/internal/generated", "github.com/vegastack/vegastack-labs/internal/localtransport", "github.com/vegastack/vegastack-labs/internal/principal", "github.com/vegastack/vegastack-labs/internal/result", "github.com/vegastack/vegastack-labs/internal/runprotocol", "github.com/vegastack/vegastack-labs/internal/serverconfig", "github.com/vegastack/vegastack-labs/internal/sshtransport", "io", "mime", "net", "runtime", "strconv", "strings", "sync", "time"}, digest: "2160a7bd6463d5ca9aa775dca3996426efc6dd8fbdd53a7fd9983ef392aa20dd"},
}

func reviewedLinuxRolePackage(c checkedSourcePackage, module, relative string) bool {
	if c.listed.ImportPath != module+"/"+relative || len(c.listed.CgoFiles) != 0 {
		return false
	}
	names := append([]string(nil), c.listed.GoFiles...)
	slices.Sort(names)
	seal, ok := linuxRoleSourceSeals[relative+"|"+strings.Join(names, ",")]
	if !ok {
		return false
	}
	imports := append([]string(nil), c.listed.Imports...)
	slices.Sort(imports)
	expected := append([]string(nil), seal.imports...)
	for i, v := range expected {
		expected[i] = strings.Replace(v, "github.com/vegastack/vegastack-labs/", module+"/", 1)
	}
	slices.Sort(expected)
	return slices.Equal(imports, expected) && digestSourceFiles(c.listed.Dir, names) == seal.digest
}
