package contractgen

import (
	"bytes"
	"encoding/json"
	"fmt"
	"sort"
	"strconv"
	"strings"

	"github.com/vegastack/vegastack-labs/internal/metadata"
)

const browserClientPath = "web/generated/read-api.ts"

func browserReadEndpoints(registry metadata.Registry) ([]metadata.EndpointDefinition, error) {
	endpoints := make([]metadata.EndpointDefinition, 0, len(registry.Endpoints))
	for _, endpoint := range registry.Endpoints {
		if endpoint.Availability != metadata.AvailabilityAvailable || endpoint.Method != "GET" {
			continue
		}
		if !strings.HasPrefix(endpoint.Path, "/api/v1/") || strings.Contains(endpoint.Path, "://") || endpoint.RequestSchema != "" {
			return nil, artifactError("GENERATED_BROWSER_ENDPOINT_UNSAFE", browserClientPath)
		}
		endpoints = append(endpoints, endpoint)
	}
	sort.Slice(endpoints, func(left, right int) bool { return endpoints[left].ID < endpoints[right].ID })
	return endpoints, nil
}

func browserSchemaGraph(registry metadata.Registry, endpoints []metadata.EndpointDefinition) ([]metadata.SchemaDefinition, error) {
	definitions := make(map[string]metadata.SchemaDefinition, len(registry.Schemas))
	for _, definition := range registry.Schemas {
		definitions[definition.ID] = definition
	}
	wanted := map[string]bool{runResultSchemaID: true}
	for _, endpoint := range endpoints {
		wanted[endpoint.DataSchema] = true
		if endpoint.QuerySchema != "" {
			wanted[endpoint.QuerySchema] = true
		}
	}
	var visit func(string) error
	visit = func(identifier string) error {
		definition, ok := definitions[identifier]
		if !ok {
			return artifactError("GENERATED_SCHEMA_MISSING", browserClientPath)
		}
		for _, field := range definition.Fields {
			if browserSecretField(field.JSONName) {
				return artifactError("GENERATED_BROWSER_SCHEMA_UNSAFE", browserClientPath)
			}
			for _, reference := range []string{field.Ref, field.ItemRef} {
				if reference == "" || wanted[reference] {
					continue
				}
				wanted[reference] = true
				if err := visit(reference); err != nil {
					return err
				}
			}
		}
		return nil
	}
	for identifier := range wanted {
		if err := visit(identifier); err != nil {
			return nil, err
		}
	}
	graph := make([]metadata.SchemaDefinition, 0, len(wanted))
	for identifier := range wanted {
		graph = append(graph, definitions[identifier])
	}
	sort.Slice(graph, func(left, right int) bool { return graph[left].ID < graph[right].ID })
	return graph, nil
}

func browserSecretField(name string) bool {
	lower := strings.ToLower(name)
	for _, forbidden := range []string{"password", "plaintext", "privatekey", "secretvalue", "credentialvalue", "accesstoken", "refreshtoken"} {
		if strings.Contains(lower, forbidden) {
			return true
		}
	}
	return false
}

type browserSchemaRule struct {
	ID     string             `json:"id"`
	Fields []browserFieldRule `json:"fields"`
}

type browserFieldRule struct {
	Name                 string             `json:"name"`
	Kind                 metadata.ValueKind `json:"kind"`
	Required             bool               `json:"required"`
	Nullable             bool               `json:"nullable"`
	Ref                  string             `json:"ref,omitempty"`
	ItemRef              string             `json:"itemRef,omitempty"`
	ItemKind             metadata.ValueKind `json:"itemKind,omitempty"`
	Enum                 []string           `json:"enum,omitempty"`
	AdditionalProperties bool               `json:"additionalProperties,omitempty"`
	Pattern              string             `json:"pattern,omitempty"`
	MinLength            *int               `json:"minLength,omitempty"`
	MaxLength            *int               `json:"maxLength,omitempty"`
	Minimum              *int64             `json:"minimum,omitempty"`
	Maximum              *int64             `json:"maximum,omitempty"`
	MinItems             *int               `json:"minItems,omitempty"`
	MaxItems             *int               `json:"maxItems,omitempty"`
	UniqueItems          bool               `json:"uniqueItems,omitempty"`
}

func renderBrowserContractGraph(endpoints []metadata.EndpointDefinition, schemas []metadata.SchemaDefinition) []byte {
	var output bytes.Buffer
	output.WriteString("// Code generated by go run ./tooling/generate-contracts --write; DO NOT EDIT.\n")
	output.WriteString("// Browser-safe available read operations:\n")
	for _, endpoint := range endpoints {
		output.WriteString("// " + endpoint.ID + "\n")
	}
	output.WriteString("\n")
	for _, schema := range schemas {
		renderBrowserType(&output, schema)
	}
	output.WriteString(`export type ApiFailureKind = "api" | "network" | "malformed-json" | "schema-mismatch" | "unsupported-version" | "cancelled";

export class ReadClientError extends Error {
  readonly kind: ApiFailureKind;
  readonly code: string;
  readonly target: string;
  readonly retryable: boolean;
  readonly correlationId: string | null;

  constructor(kind: ApiFailureKind, code: string, target: string, retryable = false, correlationId: string | null = null) {
    super(code);
    this.name = "ReadClientError";
    this.kind = kind;
    this.code = code;
    this.target = target;
    this.retryable = retryable;
    this.correlationId = correlationId;
  }
}

type SchemaRule = { readonly id: string; readonly fields: ReadonlyArray<FieldRule> };
type FieldRule = {
  readonly name: string;
  readonly kind: "string" | "boolean" | "integer" | "object" | "array";
  readonly required: boolean;
  readonly nullable: boolean;
  readonly ref?: string;
  readonly itemRef?: string;
  readonly itemKind?: "string" | "boolean" | "integer" | "object" | "array";
  readonly enum?: ReadonlyArray<string>;
  readonly additionalProperties?: boolean;
  readonly pattern?: string;
  readonly minLength?: number;
  readonly maxLength?: number;
  readonly minimum?: number;
  readonly maximum?: number;
  readonly minItems?: number;
  readonly maxItems?: number;
  readonly uniqueItems?: boolean;
};

const SCHEMAS: ReadonlyArray<SchemaRule> = `)
	rules := make([]browserSchemaRule, 0, len(schemas))
	for _, schema := range schemas {
		rule := browserSchemaRule{ID: schema.ID, Fields: make([]browserFieldRule, 0, len(schema.Fields))}
		for _, field := range schema.Fields {
			rule.Fields = append(rule.Fields, browserFieldRule{
				Name: field.JSONName, Kind: field.Kind, Required: field.Required, Nullable: field.Nullable,
				Ref: field.Ref, ItemRef: field.ItemRef, ItemKind: field.ItemKind, Enum: field.Enum,
				AdditionalProperties: field.AdditionalProperties, Pattern: field.Pattern,
				MinLength: field.MinLength, MaxLength: field.MaxLength, Minimum: field.Minimum, Maximum: field.Maximum,
				MinItems: field.MinItems, MaxItems: field.MaxItems, UniqueItems: field.UniqueItems,
			})
		}
		rules = append(rules, rule)
	}
	encoded, _ := json.MarshalIndent(rules, "", "  ")
	output.Write(encoded)
	output.WriteString(`;

function mismatch(path: string, reason: string): never {
  throw new ReadClientError("schema-mismatch", "SCHEMA_MISMATCH", path + ": " + reason);
}

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}

function stringLength(value: string): number {
  return Array.from(value).length;
}

function decodePrimitive(kind: FieldRule["kind"], value: unknown, path: string): unknown {
  if (kind === "string" && typeof value === "string") return value;
  if (kind === "boolean" && typeof value === "boolean") return value;
  if (kind === "integer" && typeof value === "number" && Number.isSafeInteger(value)) return value;
  if (kind === "object" && isRecord(value)) return value;
  if (kind === "array" && Array.isArray(value)) return value;
  return mismatch(path, "wrong value kind");
}

function decodeField(rule: FieldRule, value: unknown, path: string): unknown {
  if (value === null) {
    if (rule.nullable) return null;
    return mismatch(path, "null is not allowed");
  }
  let decoded: unknown;
  if (rule.ref) {
    decoded = decodeSchema(rule.ref, value, path);
  } else if (rule.kind === "array") {
    if (!Array.isArray(value)) return mismatch(path, "wrong value kind");
    decoded = value.map((item, index) => rule.itemRef
      ? decodeSchema(rule.itemRef, item, path + "[" + index + "]")
      : decodePrimitive(rule.itemKind ?? "object", item, path + "[" + index + "]"));
  } else {
    decoded = decodePrimitive(rule.kind, value, path);
    if (rule.kind === "object" && !rule.additionalProperties && Object.keys(decoded as object).length !== 0) {
      return mismatch(path, "additional property is not allowed");
    }
  }
  if (typeof decoded === "string") {
    const length = stringLength(decoded);
    if (rule.enum && !rule.enum.includes(decoded)) return mismatch(path, "value is not in enum");
    if (rule.pattern && !(new RegExp(rule.pattern, "u")).test(decoded)) return mismatch(path, "pattern mismatch");
    if (rule.minLength !== undefined && length < rule.minLength) return mismatch(path, "string is too short");
    if (rule.maxLength !== undefined && length > rule.maxLength) return mismatch(path, "string is too long");
  }
  if (typeof decoded === "number") {
    if (rule.minimum !== undefined && decoded < rule.minimum) return mismatch(path, "number is below minimum");
    if (rule.maximum !== undefined && decoded > rule.maximum) return mismatch(path, "number is above maximum");
  }
  if (Array.isArray(decoded)) {
    if (rule.minItems !== undefined && decoded.length < rule.minItems) return mismatch(path, "array is too short");
    if (rule.maxItems !== undefined && decoded.length > rule.maxItems) return mismatch(path, "array is too long");
    if (rule.uniqueItems) {
      const fingerprints = decoded.map((item) => JSON.stringify(item));
      if (new Set(fingerprints).size !== fingerprints.length) return mismatch(path, "array items are not unique");
    }
  }
  return decoded;
}

function decodeSchema(identifier: string, value: unknown, path = identifier): Record<string, unknown> {
  const rule = SCHEMAS.find((candidate) => candidate.id === identifier);
  if (!rule) return mismatch(path, "schema is unavailable");
  if (!isRecord(value)) return mismatch(path, "expected object");
  const fieldNames = new Set(rule.fields.map((field) => field.name));
  for (const name of Object.keys(value)) {
    if (!fieldNames.has(name)) return mismatch(path + "." + name, "additional property is not allowed");
  }
  const result: Record<string, unknown> = {};
  for (const field of rule.fields) {
    if (!(field.name in value)) {
      if (field.required) return mismatch(path + "." + field.name, "required property is missing");
      continue;
    }
    result[field.name] = decodeField(field, value[field.name], path + "." + field.name);
  }
  return result;
}

`)
	for _, schema := range schemas {
		name := schemaGoName(schema.ID)
		fmt.Fprintf(&output, "function decode%s(value: unknown): %s {\n  return decodeSchema(%s, value) as unknown as %s;\n}\n\n", name, name, strconv.Quote(schema.ID), name)
	}
	output.WriteString(`export type FetchTransport = (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
export type RequestOptions = { readonly signal?: AbortSignal };
export type ReadResult<T> = Omit<RunResult, "data"> & { readonly data: T };

function decodeReadResult<T>(value: unknown, operation: string, decodeData: (data: unknown) => T): ReadResult<T> {
  if (!isRecord(value)) return mismatch(operation, "expected result object");
  const version = value.schemaVersion;
  if (typeof version !== "string" || !/^\d+\.\d+\.\d+$/.test(version)) return mismatch(operation + ".schemaVersion", "invalid version");
  if (Number.parseInt(version.split(".")[0] ?? "", 10) !== 1) {
    throw new ReadClientError("unsupported-version", "SCHEMA_UNSUPPORTED", operation);
  }
  const envelope = decodeRunResult(value);
  const data = decodeData(envelope.data);
  return { ...envelope, data };
}

async function readJSON(response: Response, operation: string): Promise<unknown> {
  try {
    return await response.json();
  } catch {
    throw new ReadClientError("malformed-json", "MALFORMED_JSON", operation);
  }
}

export type ReadClient = {
  readonly getSummary: (options?: RequestOptions) => Promise<ReadResult<ApiSummaryData>>;
};

export function createReadClient(fetchTransport: FetchTransport): ReadClient {
  return {
    async getSummary(options = {}) {
      const operation = "api.v1.summary.get";
      const response = await fetchTransport("/api/v1/summary", { method: "GET", cache: "no-store", credentials: "same-origin", signal: options.signal });
      const value = await readJSON(response, operation);
      return decodeReadResult(value, operation, decodeApiSummaryData);
    },
  };
}
`)
	return output.Bytes()
}

func renderBrowserType(output *bytes.Buffer, schema metadata.SchemaDefinition) {
	fmt.Fprintf(output, "export interface %s {\n", schemaGoName(schema.ID))
	for _, field := range schema.Fields {
		optional := ""
		if !field.Required {
			optional = "?"
		}
		fmt.Fprintf(output, "  readonly %s%s: %s;\n", strconv.Quote(field.JSONName), optional, browserType(field))
	}
	output.WriteString("}\n\n")
}

func browserType(field metadata.FieldDefinition) string {
	var value string
	if len(field.Enum) != 0 {
		parts := make([]string, len(field.Enum))
		for index, enum := range field.Enum {
			parts[index] = strconv.Quote(enum)
		}
		value = strings.Join(parts, " | ")
	} else if field.Ref != "" {
		value = schemaGoName(field.Ref)
	} else {
		switch field.Kind {
		case metadata.ValueString:
			value = "string"
		case metadata.ValueBoolean:
			value = "boolean"
		case metadata.ValueInteger:
			value = "number"
		case metadata.ValueObject:
			value = "Readonly<Record<string, unknown>>"
		case metadata.ValueArray:
			item := "unknown"
			if field.ItemRef != "" {
				item = schemaGoName(field.ItemRef)
			} else {
				switch field.ItemKind {
				case metadata.ValueString:
					item = "string"
				case metadata.ValueBoolean:
					item = "boolean"
				case metadata.ValueInteger:
					item = "number"
				}
			}
			value = "ReadonlyArray<" + item + ">"
		}
	}
	if field.Nullable {
		value += " | null"
	}
	return value
}
