package contractgen

import (
	"bytes"
	"sort"
	"strings"

	"github.com/vegastack/vegastack-labs/internal/metadata"
)

const browserClientPath = "web/generated/read-api.ts"

func browserReadEndpoints(registry metadata.Registry) ([]metadata.EndpointDefinition, error) {
	endpoints := make([]metadata.EndpointDefinition, 0, len(registry.Endpoints))
	for _, endpoint := range registry.Endpoints {
		if endpoint.Availability != metadata.AvailabilityAvailable || endpoint.Method != "GET" {
			continue
		}
		if !strings.HasPrefix(endpoint.Path, "/api/v1/") || strings.Contains(endpoint.Path, "://") || endpoint.RequestSchema != "" {
			return nil, artifactError("GENERATED_BROWSER_ENDPOINT_UNSAFE", browserClientPath)
		}
		endpoints = append(endpoints, endpoint)
	}
	sort.Slice(endpoints, func(left, right int) bool { return endpoints[left].ID < endpoints[right].ID })
	return endpoints, nil
}

func browserSchemaGraph(registry metadata.Registry, endpoints []metadata.EndpointDefinition) ([]metadata.SchemaDefinition, error) {
	definitions := make(map[string]metadata.SchemaDefinition, len(registry.Schemas))
	for _, definition := range registry.Schemas {
		definitions[definition.ID] = definition
	}
	wanted := map[string]bool{runResultSchemaID: true}
	for _, endpoint := range endpoints {
		wanted[endpoint.DataSchema] = true
		if endpoint.QuerySchema != "" {
			wanted[endpoint.QuerySchema] = true
		}
	}
	var visit func(string) error
	visit = func(identifier string) error {
		definition, ok := definitions[identifier]
		if !ok {
			return artifactError("GENERATED_SCHEMA_MISSING", browserClientPath)
		}
		for _, field := range definition.Fields {
			if browserSecretField(field.JSONName) {
				return artifactError("GENERATED_BROWSER_SCHEMA_UNSAFE", browserClientPath)
			}
			for _, reference := range []string{field.Ref, field.ItemRef} {
				if reference == "" || wanted[reference] {
					continue
				}
				wanted[reference] = true
				if err := visit(reference); err != nil {
					return err
				}
			}
		}
		return nil
	}
	for identifier := range wanted {
		if err := visit(identifier); err != nil {
			return nil, err
		}
	}
	graph := make([]metadata.SchemaDefinition, 0, len(wanted))
	for identifier := range wanted {
		graph = append(graph, definitions[identifier])
	}
	sort.Slice(graph, func(left, right int) bool { return graph[left].ID < graph[right].ID })
	return graph, nil
}

func browserSecretField(name string) bool {
	lower := strings.ToLower(name)
	for _, forbidden := range []string{"password", "plaintext", "privatekey", "secretvalue", "credentialvalue", "accesstoken", "refreshtoken"} {
		if strings.Contains(lower, forbidden) {
			return true
		}
	}
	return false
}

func renderBrowserContractGraph(endpoints []metadata.EndpointDefinition, schemas []metadata.SchemaDefinition) []byte {
	var output bytes.Buffer
	output.WriteString("// Code generated by go run ./tooling/generate-contracts --write; DO NOT EDIT.\n")
	output.WriteString("// Browser-safe available read operations:\n")
	for _, endpoint := range endpoints {
		output.WriteString("// " + endpoint.ID + "\n")
	}
	output.WriteString("// Reachable schemas:\n")
	for _, schema := range schemas {
		output.WriteString("// " + schema.ID + "\n")
	}
	return output.Bytes()
}
