package contractgen

import (
	"bytes"
	"encoding/json"
	"go/format"
	"strconv"

	"github.com/vegastack/vegastack-labs/internal/metadata"
)

func renderGoValidators(registry metadata.Registry) ([]byte, error) {
	rules := make([]browserSchemaRule, 0, len(registry.Schemas))
	for _, schema := range registry.Schemas {
		rule := browserSchemaRule{ID: schema.ID, Fields: make([]browserFieldRule, 0, len(schema.Fields))}
		for _, field := range schema.Fields {
			rule.Fields = append(rule.Fields, browserFieldRule{Name: field.JSONName, Kind: field.Kind, Required: field.Required, Nullable: field.Nullable, Ref: field.Ref, ItemRef: field.ItemRef, ItemKind: field.ItemKind, Enum: field.Enum, AdditionalProperties: field.AdditionalProperties, Pattern: field.Pattern, MinLength: field.MinLength, MaxLength: field.MaxLength, Minimum: field.Minimum, Maximum: field.Maximum, MinItems: field.MinItems, MaxItems: field.MaxItems, UniqueItems: field.UniqueItems})
		}
		rules = append(rules, rule)
	}
	encoded, err := json.Marshal(rules)
	if err != nil || bytes.Contains(encoded, []byte("`")) {
		return nil, artifactError("GENERATED_VALIDATOR_RULES_INVALID", "internal/generated/contracts_validate_gen.go")
	}
	var output bytes.Buffer
	output.WriteString("// Code generated by go run ./tooling/generate-contracts --write; DO NOT EDIT.\n\npackage generated\n\n")
	output.WriteString("import (\n\t\"context\"\n\t\"encoding/json\"\n\t\"errors\"\n\t\"fmt\"\n\t\"regexp\"\n\t\"strings\"\n\t\"time\"\n\t\"unicode\"\n\n\t\"github.com/vegastack/vegastack-labs/internal/strictjson\"\n)\n\n")
	output.WriteString(`type ContractValidationMode string

const (
	ContractExact ContractValidationMode = "exact"
	ContractCompatibleRead ContractValidationMode = "compatible-read"
)

type contractSchemaRule struct { ID string ` + "`json:\"id\"`" + `; Fields []contractFieldRule ` + "`json:\"fields\"`" + ` }
type contractFieldRule struct {
	Name string ` + "`json:\"name\"`" + `; Kind string ` + "`json:\"kind\"`" + `; Required bool ` + "`json:\"required\"`" + `; Nullable bool ` + "`json:\"nullable\"`" + `
	Ref string ` + "`json:\"ref\"`" + `; ItemRef string ` + "`json:\"itemRef\"`" + `; ItemKind string ` + "`json:\"itemKind\"`" + `; Enum []string ` + "`json:\"enum\"`" + `
	AdditionalProperties bool ` + "`json:\"additionalProperties\"`" + `; Pattern string ` + "`json:\"pattern\"`" + `
	MinLength *int ` + "`json:\"minLength\"`" + `; MaxLength *int ` + "`json:\"maxLength\"`" + `; Minimum *int64 ` + "`json:\"minimum\"`" + `; Maximum *int64 ` + "`json:\"maximum\"`" + `
	MinItems *int ` + "`json:\"minItems\"`" + `; MaxItems *int ` + "`json:\"maxItems\"`" + `; UniqueItems bool ` + "`json:\"uniqueItems\"`" + `
}

const contractRulesJSON = ` + "`" + string(encoded) + "`" + `

var contractRules = func() map[string]contractSchemaRule {
	var values []contractSchemaRule
	if err := json.Unmarshal([]byte(contractRulesJSON), &values); err != nil { panic("invalid generated contract rules") }
	result := make(map[string]contractSchemaRule, len(values))
	for _, value := range values { result[value.ID] = value }
	return result
}()

func ValidateContractJSON(schemaID string, document []byte, mode ContractValidationMode) error {
	if mode != ContractExact && mode != ContractCompatibleRead { return errors.New("invalid contract validation mode") }
	if err := strictjson.Scan(context.Background(), document, strictjson.Limits{MaxDepth: 32}); err != nil { return errors.New("invalid strict JSON") }
	var value any
	decoder := json.NewDecoder(strings.NewReader(string(document))); decoder.UseNumber()
	if err := decoder.Decode(&value); err != nil { return errors.New("invalid JSON") }
	if mode == ContractCompatibleRead {
		object, ok := value.(map[string]any); if !ok { return errors.New("compatible contract must be an object") }
		contractVersion, ok := object["schemaVersion"].(string); if !ok || !regexp.MustCompile("^1\\.[0-9]+\\.[0-9]+$").MatchString(contractVersion) { return errors.New("unsupported contract major") }
	}
	return validateContractValue(schemaID, value, schemaID, mode, true)
}

func validateContractValue(schemaID string, value any, path string, mode ContractValidationMode, root bool) error {
	rule, ok := contractRules[schemaID]; if !ok { return fmt.Errorf("unknown schema at %s", path) }
	object, ok := value.(map[string]any); if !ok { return fmt.Errorf("expected object at %s", path) }
	fields := make(map[string]contractFieldRule, len(rule.Fields)); for _, field := range rule.Fields { fields[field.Name] = field }
	for name := range object {
		if _, known := fields[name]; known { continue }
		if mode != ContractCompatibleRead || !root || unsafeContractAddition(name) || unsafeContractValue(object[name]) { return fmt.Errorf("additional property at %s.%s", path, name) }
	}
	for _, field := range rule.Fields {
		fieldValue, present := object[field.Name]
		if !present { if field.Required { return fmt.Errorf("required property at %s.%s", path, field.Name) }; continue }
		if fieldValue == nil { if field.Nullable { continue }; return fmt.Errorf("null at %s.%s", path, field.Name) }
		if err := validateContractField(field, fieldValue, path+"."+field.Name, mode); err != nil { return err }
	}
	return nil
}

func validateContractField(rule contractFieldRule, value any, path string, mode ContractValidationMode) error {
	if rule.Ref != "" { return validateContractValue(rule.Ref, value, path, ContractExact, false) }
	switch rule.Kind {
	case "string":
		text, ok := value.(string); if !ok { return fmt.Errorf("wrong kind at %s", path) }
		if rule.Pattern != "" && !regexp.MustCompile(rule.Pattern).MatchString(text) { return fmt.Errorf("pattern mismatch at %s", path) }
		length := len([]rune(text)); if rule.MinLength != nil && length < *rule.MinLength { return fmt.Errorf("too short at %s", path) }; if rule.MaxLength != nil && length > *rule.MaxLength { return fmt.Errorf("too long at %s", path) }
		if len(rule.Enum) != 0 && !(mode == ContractCompatibleRead && rule.Name == "schemaVersion") { found := false; for _, candidate := range rule.Enum { found = found || candidate == text }; if !found { return fmt.Errorf("unknown state or value at %s", path) } }
	case "boolean": if _, ok := value.(bool); !ok { return fmt.Errorf("wrong kind at %s", path) }
	case "integer":
		number, ok := value.(json.Number); if !ok { return fmt.Errorf("wrong kind at %s", path) }; integer, err := number.Int64(); if err != nil { return fmt.Errorf("invalid integer at %s", path) }
		if rule.Minimum != nil && integer < *rule.Minimum { return fmt.Errorf("below minimum at %s", path) }; if rule.Maximum != nil && integer > *rule.Maximum { return fmt.Errorf("above maximum at %s", path) }
	case "object": object, ok := value.(map[string]any); if !ok { return fmt.Errorf("wrong kind at %s", path) }; if !rule.AdditionalProperties && len(object) != 0 { return fmt.Errorf("additional property at %s", path) }; if mode == ContractCompatibleRead && rule.AdditionalProperties && unsafeContractValue(object) { return fmt.Errorf("unsafe compatible value at %s", path) }
	case "array":
		values, ok := value.([]any); if !ok { return fmt.Errorf("wrong kind at %s", path) }; if rule.MinItems != nil && len(values) < *rule.MinItems { return fmt.Errorf("too few items at %s", path) }; if rule.MaxItems != nil && len(values) > *rule.MaxItems { return fmt.Errorf("too many items at %s", path) }
		seen := map[string]bool{}; for index, item := range values { itemPath := fmt.Sprintf("%s[%d]", path, index); if rule.ItemRef != "" { if err := validateContractValue(rule.ItemRef, item, itemPath, ContractExact, false); err != nil { return err } } else if err := validatePrimitiveKind(rule.ItemKind, item, itemPath); err != nil { return err }; if rule.UniqueItems { raw, _ := json.Marshal(item); key := string(raw); if seen[key] { return fmt.Errorf("duplicate item at %s", itemPath) }; seen[key] = true } }
	default: return fmt.Errorf("invalid generated rule at %s", path)
	}
	return nil
}

func validatePrimitiveKind(kind string, value any, path string) error {
	switch kind { case "string": if _, ok := value.(string); ok { return nil }; case "boolean": if _, ok := value.(bool); ok { return nil }; case "integer": if number, ok := value.(json.Number); ok { if _, err := number.Int64(); err == nil { return nil } } }
	return fmt.Errorf("wrong item kind at %s", path)
}

func unsafeContractAddition(name string) bool {
	var compact strings.Builder; for _, character := range strings.ToLower(name) { if unicode.IsLetter(character) || unicode.IsDigit(character) { compact.WriteRune(character) } }
	for _, forbidden := range []string{"password", "passwd", "passphrase", "plaintext", "privatekey", "secret", "credential", "token", "apikey", "accesskey", "bearer", "authorization", "cookie", "jwt"} { if strings.Contains(compact.String(), forbidden) { return true } }
	return false
}

func unsafeContractValue(value any) bool {
	stack := []any{value}
	for visited := 0; len(stack) != 0; visited++ {
		if visited >= 65536 { return true }
		last := len(stack)-1; current := stack[last]; stack = stack[:last]
		switch typed := current.(type) {
		case map[string]any:
			for name, nested := range typed { if unsafeContractAddition(name) { return true }; stack = append(stack, nested) }
		case []any:
			stack = append(stack, typed...)
		}
	}
	return false
}

func ValidateRunTransition(from, to string) error {
	for _, transition := range RunTransitions { if transition.From == from && transition.To == to { return nil } }
	return errors.New("invalid run transition")
}

func ValidatePlanTiming(plan Plan) error {
	created, err := time.Parse(time.RFC3339, plan.CreatedAt); if err != nil { return errors.New("invalid plan creation time") }; expires, err := time.Parse(time.RFC3339, plan.ExpiresAt); if err != nil || !expires.Equal(created.Add(time.Duration(PlanValiditySeconds)*time.Second)) { return errors.New("plan expiry must be exactly 30 minutes") }; return nil
}

func ValidateLeaseTiming(lease ExecutorLease) error {
	claimed, err := time.Parse(time.RFC3339, lease.ClaimedAt); if err != nil { return errors.New("invalid lease claim time") }; renew, err := time.Parse(time.RFC3339, lease.RenewAfter); if err != nil || !renew.Equal(claimed.Add(time.Duration(ExecutorCheckInSeconds)*time.Second)) { return errors.New("lease check-in must be exactly 20 seconds") }; expires, err := time.Parse(time.RFC3339, lease.LeaseExpiresAt); if err != nil || !expires.Equal(claimed.Add(time.Duration(ExecutorLeaseSeconds)*time.Second)) { return errors.New("lease expiry must be exactly 60 seconds") }; maximum, err := time.Parse(time.RFC3339, lease.MaximumExpiresAt); if err != nil || !maximum.Equal(expires) { return errors.New("lease maximum expiry must match its 60-second authority window") }; return nil
}

func ValidateExecutorLeaseBinding(plan Plan, run Run, lease ExecutorLease) error {
	if plan.PlanID != run.PlanID || plan.PlanID != lease.PlanID || plan.PlanDigest != run.PlanDigest || plan.PlanDigest != lease.PlanDigest || plan.Binding.RecoveryEpoch != run.RecoveryEpoch || plan.Binding.RecoveryEpoch != lease.RecoveryEpoch || plan.Binding.StateRevision != run.StateRevision || run.RunID != lease.RunID || plan.ExecutorMode != run.ExecutorMode || run.ExecutorID != lease.ExecutorID || run.ExecutorBindingDigest != lease.BindingDigest { return errors.New("executor lease widens or changes its plan/run binding") }
	if plan.ExecutorMode == "external" && (plan.ExecutorID == nil || *plan.ExecutorID != run.ExecutorID) { return errors.New("external executor lease does not match plan executor") }
	stepMatches := 0
	var step RunStep
	for _, candidate := range run.Steps { if candidate.StepID == lease.StepID { stepMatches++; step = candidate } }
	if stepMatches != 1 { return errors.New("executor lease must name exactly one run step") }
	operationMatches := 0
	for _, operation := range plan.Operations {
		if operation.OperationID != lease.OperationID { continue }
		operationMatches++
		if operation.Sequence != step.Sequence || operation.OperationID != step.OperationID || operation.OperationType != step.OperationType || operation.ExecutorID != step.ExecutorID || operation.AdapterID != step.AdapterID || operation.TargetID != step.TargetID || operation.InputDigest != step.InputDigest || operation.ArtifactDigest != step.ArtifactDigest || operation.Idempotent != step.Idempotent { return errors.New("run step widens or changes its plan operation") }
		if step.ExecutorID != lease.ExecutorID || step.AdapterID != lease.AdapterID || step.TargetID != lease.TargetID || step.ArtifactDigest != lease.ArtifactDigest { return errors.New("executor lease widens or changes its run step") }
	}
	if operationMatches != 1 { return errors.New("executor lease operation must name exactly one plan operation") }
	return nil
}

func ValidateExecutionReceiptBinding(lease ExecutorLease, receipt ExecutionReceipt) error {
	if lease.LeaseID != receipt.LeaseID || lease.PlanID != receipt.PlanID || lease.PlanDigest != receipt.PlanDigest || lease.RunID != receipt.RunID || lease.StepID != receipt.StepID || lease.OperationID != receipt.OperationID || lease.ExecutorID != receipt.ExecutorID || lease.AdapterID != receipt.AdapterID || lease.TargetID != receipt.TargetID || lease.ArtifactDigest != receipt.ArtifactDigest || lease.BindingDigest != receipt.BindingDigest || lease.NonceDigest != receipt.NonceDigest || lease.RecoveryEpoch != receipt.RecoveryEpoch { return errors.New("execution receipt widens or changes its lease binding") }
	return nil
}
`)
	formatted, err := format.Source(output.Bytes())
	if err != nil {
		return nil, artifactError("GENERATED_GO_INVALID", "internal/generated/contracts_validate_gen.go:"+strconv.Itoa(len(output.Bytes())))
	}
	return formatted, nil
}
