package contractgen

import (
	"bytes"
	"encoding/json"
	"go/format"
	"strconv"

	"github.com/vegastack/vegastack-labs/internal/metadata"
)

func renderGoValidators(registry metadata.Registry) ([]byte, error) {
	rules := make([]browserSchemaRule, 0, len(registry.Schemas))
	for _, schema := range registry.Schemas {
		rule := browserSchemaRule{ID: schema.ID, Fields: make([]browserFieldRule, 0, len(schema.Fields))}
		for _, field := range schema.Fields {
			rule.Fields = append(rule.Fields, browserFieldRule{Name: field.JSONName, Kind: field.Kind, Required: field.Required, Nullable: field.Nullable, Ref: field.Ref, ItemRef: field.ItemRef, ItemKind: field.ItemKind, Enum: field.Enum, AdditionalProperties: field.AdditionalProperties, Pattern: field.Pattern, MinLength: field.MinLength, MaxLength: field.MaxLength, Minimum: field.Minimum, Maximum: field.Maximum, MinItems: field.MinItems, MaxItems: field.MaxItems, UniqueItems: field.UniqueItems})
		}
		rules = append(rules, rule)
	}
	encoded, err := json.Marshal(rules)
	if err != nil || bytes.Contains(encoded, []byte("`")) {
		return nil, artifactError("GENERATED_VALIDATOR_RULES_INVALID", "internal/generated/contracts_validate_gen.go")
	}
	var output bytes.Buffer
	output.WriteString("// Code generated by go run ./tooling/generate-contracts --write; DO NOT EDIT.\n\npackage generated\n\n")
	output.WriteString("import (\n\t\"context\"\n\t\"encoding/json\"\n\t\"errors\"\n\t\"fmt\"\n\t\"regexp\"\n\t\"strings\"\n\t\"time\"\n\t\"unicode\"\n\n\t\"github.com/vegastack/vegastack-labs/internal/strictjson\"\n)\n\n")
	output.WriteString(`type ContractValidationMode string

const (
	ContractExact ContractValidationMode = "exact"
	ContractCompatibleRead ContractValidationMode = "compatible-read"
)

type contractSchemaRule struct { ID string ` + "`json:\"id\"`" + `; Fields []contractFieldRule ` + "`json:\"fields\"`" + ` }
type contractFieldRule struct {
	Name string ` + "`json:\"name\"`" + `; Kind string ` + "`json:\"kind\"`" + `; Required bool ` + "`json:\"required\"`" + `; Nullable bool ` + "`json:\"nullable\"`" + `
	Ref string ` + "`json:\"ref\"`" + `; ItemRef string ` + "`json:\"itemRef\"`" + `; ItemKind string ` + "`json:\"itemKind\"`" + `; Enum []string ` + "`json:\"enum\"`" + `
	AdditionalProperties bool ` + "`json:\"additionalProperties\"`" + `; Pattern string ` + "`json:\"pattern\"`" + `
	MinLength *int ` + "`json:\"minLength\"`" + `; MaxLength *int ` + "`json:\"maxLength\"`" + `; Minimum *int64 ` + "`json:\"minimum\"`" + `; Maximum *int64 ` + "`json:\"maximum\"`" + `
	MinItems *int ` + "`json:\"minItems\"`" + `; MaxItems *int ` + "`json:\"maxItems\"`" + `; UniqueItems bool ` + "`json:\"uniqueItems\"`" + `
}

const contractRulesJSON = ` + "`" + string(encoded) + "`" + `

var contractRules = func() map[string]contractSchemaRule {
	var values []contractSchemaRule
	if err := json.Unmarshal([]byte(contractRulesJSON), &values); err != nil { panic("invalid generated contract rules") }
	result := make(map[string]contractSchemaRule, len(values))
	for _, value := range values { result[value.ID] = value }
	return result
}()

func ValidateContractJSON(schemaID string, document []byte, mode ContractValidationMode) error {
	if mode != ContractExact && mode != ContractCompatibleRead { return errors.New("invalid contract validation mode") }
	if err := strictjson.Scan(context.Background(), document, strictjson.Limits{MaxDepth: 32}); err != nil { return errors.New("invalid strict JSON") }
	var value any
	decoder := json.NewDecoder(strings.NewReader(string(document))); decoder.UseNumber()
	if err := decoder.Decode(&value); err != nil { return errors.New("invalid JSON") }
	if mode == ContractCompatibleRead {
		object, ok := value.(map[string]any); if !ok { return errors.New("compatible contract must be an object") }
		contractVersion, ok := object["schemaVersion"].(string); if !ok || !regexp.MustCompile("^1\\.[0-9]+\\.[0-9]+$").MatchString(contractVersion) { return errors.New("unsupported contract major") }
	}
	if err := validateContractValue(schemaID, value, schemaID, mode, true); err != nil { return err }
 if schemaID == SchemaIDCredentialLifecycleRequest {
  var request CredentialLifecycleRequest
  if json.Unmarshal(document, &request) != nil { return errors.New(ErrorCodeInputInvalid) }
  return ValidateLifecycleRequestSemantics(request)
 }
 return nil
}

// ValidateLifecycleRequestSemantics enforces action-dependent metadata rules at
// typed service calls and every generated JSON decode boundary.
func ValidateLifecycleRequestSemantics(request CredentialLifecycleRequest) error {
 invalid := func() error { return errors.New(ErrorCodeInputInvalid) }
 identifier := regexp.MustCompile("^[a-z][a-z0-9._:-]{0,127}$")
 digest := regexp.MustCompile("^sha256:[a-f0-9]{64}$")
 if request.Schema != SchemaIDCredentialLifecycleRequest || request.SchemaVersion != "1.3.0" || request.ExpectedStateRevision < 0 || request.RecoveryEpoch < 0 || !digest.MatchString(request.TargetDigest) || !identifier.MatchString(request.IdempotencyKey) { return invalid() }
 for _, id := range []string{request.ReferenceID, request.MaterialVersion, request.ResolverID, request.TargetID} { if !identifier.MatchString(id) { return invalid() } }
 for _, id := range []*string{request.DraftID, request.PriorMaterialVersion} { if id != nil && !identifier.MatchString(*id) { return invalid() } }
 seen := map[string]bool{}
 if len(request.ConsumerIDs) > 64 || len(request.RequiredDeniedConsumerIDs) > 64 { return invalid() }
 for _, id := range append(append([]string(nil), request.ConsumerIDs...), request.RequiredDeniedConsumerIDs...) { if !identifier.MatchString(id) || seen[id] { return invalid() }; seen[id] = true }
 nativeOperation := request.ResolverID == "native-systemd" && (request.Action == "credential.activate" || request.Action == "credential.rotate")
 if !nativeOperation {
  if request.NativeConsumers != nil && len(*request.NativeConsumers) != 0 || request.NativeDeniedReaders != nil && len(*request.NativeDeniedReaders) != 0 { return invalid() }
 } else {
  if request.NativeConsumers == nil || request.NativeDeniedReaders == nil || len(*request.NativeConsumers) != len(request.ConsumerIDs) || len(*request.NativeDeniedReaders) != len(request.RequiredDeniedConsumerIDs) { return invalid() }
  machineID := regexp.MustCompile("^[0-9a-f]{32}$")
  unitName := regexp.MustCompile("^[a-z0-9][a-z0-9_.@-]{0,119}\\.service$")
  positive := map[string]bool{}
  positiveUID := map[int64]bool{}
  positiveUnits := map[struct{ host, unit string }]bool{}
  for _, id := range request.ConsumerIDs { positive[id] = true }
  host := ""
  for _, item := range *request.NativeConsumers {
   if item.Schema != SchemaIDCredentialNativeConsumer || item.SchemaVersion != "1.0.0" || !positive[item.ConsumerID] || item.TargetID != request.TargetID || !machineID.MatchString(item.HostMachineID) || !unitName.MatchString(item.UnitName) || strings.Contains(item.UnitName, "..") || item.ServiceUID <= 0 || item.ServiceUID > 4294967295 || item.ServiceGID <= 0 || item.ServiceGID > 4294967295 || !identifier.MatchString(item.ProfileID) || !identifier.MatchString(item.RoleID) { return invalid() }
   if host != "" && item.HostMachineID != host { return invalid() }; host = item.HostMachineID
   unitKey := struct{ host, unit string }{item.HostMachineID, item.UnitName}
   if positiveUnits[unitKey] { return invalid() }; positiveUnits[unitKey] = true
   delete(positive, item.ConsumerID); positiveUID[item.ServiceUID] = true
  }
  if len(positive) != 0 { return invalid() }
  denied := map[string]bool{}
  deniedReaders := map[struct { host string; uid, gid int64 }]bool{}
  for _, id := range request.RequiredDeniedConsumerIDs { denied[id] = true }
  for _, item := range *request.NativeDeniedReaders {
   if item.Schema != SchemaIDCredentialNativeDeniedReader || item.SchemaVersion != "1.0.0" || !denied[item.ConsumerID] || item.TargetID != request.TargetID || item.HostMachineID != host || item.ReaderUID <= 0 || item.ReaderUID > 4294967295 || item.ReaderGID <= 0 || item.ReaderGID > 4294967295 || positiveUID[item.ReaderUID] || !identifier.MatchString(item.ProfileID) || !identifier.MatchString(item.RoleID) { return invalid() }
   readerKey := struct { host string; uid, gid int64 }{item.HostMachineID, item.ReaderUID, item.ReaderGID}
   if deniedReaders[readerKey] { return invalid() }; deniedReaders[readerKey] = true
   delete(denied, item.ConsumerID)
  }
  if len(denied) != 0 { return invalid() }
 }
 noRecovery := request.PriorRecoveryEpoch == nil && request.CustodyProofDigest == nil && request.FormerControllerFenceDigest == nil
 switch request.Action {
 case "credential.stage":
  if request.DraftID == nil || len(request.ConsumerIDs) == 0 || len(request.RequiredDeniedConsumerIDs) != 0 || request.PriorMaterialVersion != nil || request.OverlapSeconds != 0 || !noRecovery { return invalid() }
 case "credential.activate":
  if request.DraftID != nil || len(request.ConsumerIDs) == 0 || len(request.RequiredDeniedConsumerIDs) == 0 || request.PriorMaterialVersion != nil || request.OverlapSeconds != 0 || !noRecovery { return invalid() }
 case "credential.rotate":
  if request.DraftID == nil || len(request.ConsumerIDs) == 0 || len(request.RequiredDeniedConsumerIDs) == 0 || request.PriorMaterialVersion == nil || *request.PriorMaterialVersion == request.MaterialVersion || request.OverlapSeconds < 0 || request.OverlapSeconds > 3600 || !noRecovery { return invalid() }
 case "credential.revoke":
  if request.DraftID != nil || len(request.ConsumerIDs) != 0 || len(request.RequiredDeniedConsumerIDs) != 0 || request.PriorMaterialVersion != nil || request.OverlapSeconds != 0 || !noRecovery { return invalid() }
 case "credential.recover":
  if request.DraftID == nil || len(request.ConsumerIDs) == 0 || len(request.RequiredDeniedConsumerIDs) != 0 || request.PriorMaterialVersion != nil || request.OverlapSeconds != 0 || request.PriorRecoveryEpoch == nil || *request.PriorRecoveryEpoch < 0 || request.RecoveryEpoch <= *request.PriorRecoveryEpoch || request.CustodyProofDigest == nil || !digest.MatchString(*request.CustodyProofDigest) || request.FormerControllerFenceDigest == nil || !digest.MatchString(*request.FormerControllerFenceDigest) { return invalid() }
 default: return invalid()
 }
 return nil
}

func contractInt(value map[string]any, name string) int64 {
	number, _ := value[name].(json.Number); result, _ := number.Int64(); return result
}

func validatePhase5Relations(schemaID string, value any) error {
	object, ok := value.(map[string]any); if !ok { return errors.New("Phase 5 contract is not an object") }
	switch schemaID {
	case SchemaIDGateEvidence, SchemaIDBackupJob, SchemaIDRecoveryPoint, SchemaIDAuditCheckpoint:
		if object["sourceKind"] == "fixture" && object["proofClass"] != "fixture" { return errors.New("fixture source cannot claim live proof") }
	}
	switch schemaID {
	case SchemaIDGateEvidence:
		observed, err := time.Parse(time.RFC3339, object["observedAt"].(string)); if err != nil { return errors.New("invalid evidence observation time") }
		expires, err := time.Parse(time.RFC3339, object["expiresAt"].(string)); if err != nil || !expires.After(observed) { return errors.New("evidence expiry does not follow observation") }
	case SchemaIDGateEvaluation:
		if object["outcome"] == "passed" && len(object["evidenceIds"].([]any)) == 0 { return errors.New("passed gate has no evidence") }
	case SchemaIDBackupJob:
		if object["status"] == "verified" && (object["pointId"] == nil || object["verificationDigest"] == nil) { return errors.New("verified backup lacks point or verification") }
	case SchemaIDRecoveryPoint:
		if object["verificationStatus"] == "verified" && object["verifiedAt"] == nil { return errors.New("verified recovery point lacks verification time") }
	case SchemaIDAuditCheckpoint:
		if contractInt(object, "lastEventId") < contractInt(object, "firstEventId") { return errors.New("audit checkpoint event range is reversed") }
		if object["schemaVersion"] == "1.1.0" && contractInt(object, "lastSegmentSequence") < contractInt(object, "firstSegmentSequence") { return errors.New("audit checkpoint segment range is reversed") }
		if object["verificationStatus"] == "verified" && object["verifiedAt"] == nil { return errors.New("verified checkpoint lacks verification time") }
		if object["sourceKind"] == "independent" && object["proofClass"] == "live" && object["independentCopyDigest"] == nil { return errors.New("independent checkpoint lacks copy digest") }
		if object["schemaVersion"] == "1.1.0" && object["status"] == "anchored" && (object["signatureDigest"] == nil || object["publicKeyId"] == nil || object["exportReceiptDigest"] == nil || object["independentReadDigest"] == nil) { return errors.New("anchored checkpoint lacks independent binding") }
	case SchemaIDRestoreBinding:
		if contractInt(object, "nextRecoveryEpoch") != contractInt(object, "priorRecoveryEpoch")+1 { return errors.New("recovery epoch must increment once") }
		if object["newInstanceId"] == object["priorInstanceId"] { return errors.New("restored controller must have a new instance") }
	case SchemaIDRestoreRunRequest:
		if contractInt(object, "recoveryEpoch") != contractInt(object, "priorRecoveryEpoch") || contractInt(object, "nextRecoveryEpoch") != contractInt(object, "priorRecoveryEpoch")+1 { return errors.New("restore request epoch mismatch") }
		if object["newInstanceId"] == object["priorInstanceId"] { return errors.New("restore request reuses controller instance") }
	case SchemaIDRestoreVerifyRequest:
		if contractInt(object, "recoveryEpoch") != contractInt(object, "nextRecoveryEpoch") { return errors.New("restore verification epoch mismatch") }
	case SchemaIDRestoreVerification:
		if object["status"] == "verified" && (object["fenceVerified"] != true || object["databaseVerified"] != true || object["auditVerified"] != true || object["verifiedAt"] == nil) { return errors.New("restore verification is incomplete") }
	}
	return nil
}

func validateContractValue(schemaID string, value any, path string, mode ContractValidationMode, root bool) error {
	rule, ok := contractRules[schemaID]; if !ok { return fmt.Errorf("unknown schema at %s", path) }
	object, ok := value.(map[string]any); if !ok { return fmt.Errorf("expected object at %s", path) }
	credentialV10 := root && mode == ContractCompatibleRead && schemaID == SchemaIDCredentialReference && object["schemaVersion"] == "1.0.0"
	auditCheckpointV10 := root && mode == ContractCompatibleRead && schemaID == SchemaIDAuditCheckpoint && object["schemaVersion"] == "1.0.0"
	if credentialV10 && object["status"] == "staged" { return fmt.Errorf("unknown state or value at %s.status", path) }
	fields := make(map[string]contractFieldRule, len(rule.Fields)); for _, field := range rule.Fields { fields[field.Name] = field }
	for name := range object {
		if _, known := fields[name]; known { continue }
		if mode != ContractCompatibleRead || !root || unsafeContractAddition(name) || unsafeContractValue(object[name]) { return fmt.Errorf("additional property at %s.%s", path, name) }
	}
	for _, field := range rule.Fields {
		fieldValue, present := object[field.Name]
		if !present { if field.Required && !(credentialV10 && credentialReferenceV10OmittedField(field.Name)) && !(auditCheckpointV10 && auditCheckpointV10OmittedField(field.Name)) { return fmt.Errorf("required property at %s.%s", path, field.Name) }; continue }
		if fieldValue == nil { if field.Nullable { continue }; return fmt.Errorf("null at %s.%s", path, field.Name) }
		if err := validateContractField(field, fieldValue, path+"."+field.Name, mode); err != nil { return err }
	}
	return validatePhase5Relations(schemaID, object)
}

func credentialReferenceV10OmittedField(name string) bool {
	switch name { case "targetId", "resolverId", "stateRevision", "activatedAt", "verifiedConsumerIds": return true; default: return false }
}

func auditCheckpointV10OmittedField(name string) bool {
	switch name { case "instanceId", "firstSegmentSequence", "lastSegmentSequence", "signerReferenceId", "signerMaterialVersion", "signatureDigest", "publicKeyId", "exportReceiptDigest", "independentReadDigest", "status", "reasonCode", "preAnchor": return true; default: return false }
}

func validateContractField(rule contractFieldRule, value any, path string, mode ContractValidationMode) error {
	if rule.Ref != "" { return validateContractValue(rule.Ref, value, path, ContractExact, false) }
	switch rule.Kind {
	case "string":
		text, ok := value.(string); if !ok { return fmt.Errorf("wrong kind at %s", path) }
		if rule.Pattern != "" && !regexp.MustCompile(rule.Pattern).MatchString(text) { return fmt.Errorf("pattern mismatch at %s", path) }
		length := len([]rune(text)); if rule.MinLength != nil && length < *rule.MinLength { return fmt.Errorf("too short at %s", path) }; if rule.MaxLength != nil && length > *rule.MaxLength { return fmt.Errorf("too long at %s", path) }
		if len(rule.Enum) != 0 && !(mode == ContractCompatibleRead && rule.Name == "schemaVersion") { found := false; for _, candidate := range rule.Enum { found = found || candidate == text }; if !found { return fmt.Errorf("unknown state or value at %s", path) } }
	case "boolean": if _, ok := value.(bool); !ok { return fmt.Errorf("wrong kind at %s", path) }
	case "integer":
		number, ok := value.(json.Number); if !ok { return fmt.Errorf("wrong kind at %s", path) }; integer, err := number.Int64(); if err != nil { return fmt.Errorf("invalid integer at %s", path) }
		if rule.Minimum != nil && integer < *rule.Minimum { return fmt.Errorf("below minimum at %s", path) }; if rule.Maximum != nil && integer > *rule.Maximum { return fmt.Errorf("above maximum at %s", path) }
	case "object": object, ok := value.(map[string]any); if !ok { return fmt.Errorf("wrong kind at %s", path) }; if !rule.AdditionalProperties && len(object) != 0 { return fmt.Errorf("additional property at %s", path) }; if mode == ContractCompatibleRead && rule.AdditionalProperties && unsafeContractValue(object) { return fmt.Errorf("unsafe compatible value at %s", path) }
	case "array":
		values, ok := value.([]any); if !ok { return fmt.Errorf("wrong kind at %s", path) }; if rule.MinItems != nil && len(values) < *rule.MinItems { return fmt.Errorf("too few items at %s", path) }; if rule.MaxItems != nil && len(values) > *rule.MaxItems { return fmt.Errorf("too many items at %s", path) }
		seen := map[string]bool{}; for index, item := range values { itemPath := fmt.Sprintf("%s[%d]", path, index); if rule.ItemRef != "" { if err := validateContractValue(rule.ItemRef, item, itemPath, ContractExact, false); err != nil { return err } } else if err := validatePrimitiveKind(rule.ItemKind, item, itemPath); err != nil { return err }; if rule.UniqueItems { raw, _ := json.Marshal(item); key := string(raw); if seen[key] { return fmt.Errorf("duplicate item at %s", itemPath) }; seen[key] = true } }
	default: return fmt.Errorf("invalid generated rule at %s", path)
	}
	return nil
}

func validatePrimitiveKind(kind string, value any, path string) error {
	switch kind { case "string": if _, ok := value.(string); ok { return nil }; case "boolean": if _, ok := value.(bool); ok { return nil }; case "integer": if number, ok := value.(json.Number); ok { if _, err := number.Int64(); err == nil { return nil } } }
	return fmt.Errorf("wrong item kind at %s", path)
}

func unsafeContractAddition(name string) bool {
	var compact strings.Builder; for _, character := range strings.ToLower(name) { if unicode.IsLetter(character) || unicode.IsDigit(character) { compact.WriteRune(character) } }
	for _, forbidden := range []string{"password", "passwd", "passphrase", "plaintext", "privatekey", "secret", "credential", "token", "apikey", "accesskey", "bearer", "authorization", "cookie", "jwt"} { if strings.Contains(compact.String(), forbidden) { return true } }
	return false
}

func unsafeContractValue(value any) bool {
	stack := []any{value}
	for visited := 0; len(stack) != 0; visited++ {
		if visited >= 65536 { return true }
		last := len(stack)-1; current := stack[last]; stack = stack[:last]
		switch typed := current.(type) {
		case map[string]any:
			for name, nested := range typed { if unsafeContractAddition(name) { return true }; stack = append(stack, nested) }
		case []any:
			stack = append(stack, typed...)
		}
	}
	return false
}

func ValidateRunTransition(from, to string) error {
	for _, transition := range RunTransitions { if transition.From == from && transition.To == to { return nil } }
	return errors.New("invalid run transition")
}

func ValidatePhase5Transition(kind, from, to string) error {
	var transitions []RunTransition
	switch kind {
	case "gate-evidence": transitions = GateEvidenceTransitions
	case "backup-job": transitions = BackupJobTransitions
	case "restore": transitions = RestoreTransitions
	case "scheduled-job": transitions = ScheduledJobTransitions
	default: return errors.New("unknown Phase 5 lifecycle")
	}
	for _, transition := range transitions { if transition.From == from && transition.To == to { return nil } }
	return errors.New("invalid Phase 5 transition")
}

func ValidateScheduledJobBinding(policy ScheduledJobPolicy, job ScheduledJob) error {
	if !policy.Enabled || len(policy.ExactTargetIDs) == 0 ||
		policy.PolicyID != job.PolicyID || policy.Revision != job.PolicyRevision ||
		policy.ActionDigest != job.ActionDigest || policy.TargetDigest != job.TargetDigest ||
		policy.RecoveryEpoch != job.RecoveryEpoch {
		return errors.New("scheduled job widens or changes its exact policy")
	}
	return nil
}

func ValidateScheduledJobRequestBinding(policy ScheduledJobPolicy, request ScheduledJobRequest) error {
	if !policy.Enabled || len(policy.ExactTargetIDs) == 0 ||
		policy.PolicyID != request.PolicyID || policy.Revision != request.PolicyRevision ||
		policy.ActionDigest != request.ActionDigest || policy.TargetDigest != request.TargetDigest ||
		policy.RecoveryEpoch != request.RecoveryEpoch {
		return errors.New("scheduled request widens or changes its exact policy")
	}
	return nil
}

func ValidatePlanTiming(plan Plan) error {
	created, err := time.Parse(time.RFC3339, plan.CreatedAt); if err != nil { return errors.New("invalid plan creation time") }; expires, err := time.Parse(time.RFC3339, plan.ExpiresAt); if err != nil || !expires.Equal(created.Add(time.Duration(PlanValiditySeconds)*time.Second)) { return errors.New("plan expiry must be exactly 30 minutes") }; return nil
}

func ValidateLeaseTiming(lease ExecutorLease) error {
	claimed, err := time.Parse(time.RFC3339, lease.ClaimedAt); if err != nil { return errors.New("invalid lease claim time") }; renew, err := time.Parse(time.RFC3339, lease.RenewAfter); if err != nil || !renew.Equal(claimed.Add(time.Duration(ExecutorCheckInSeconds)*time.Second)) { return errors.New("lease check-in must be exactly 20 seconds") }; expires, err := time.Parse(time.RFC3339, lease.LeaseExpiresAt); if err != nil || !expires.Equal(claimed.Add(time.Duration(ExecutorLeaseSeconds)*time.Second)) { return errors.New("lease expiry must be exactly 60 seconds") }; maximum, err := time.Parse(time.RFC3339, lease.MaximumExpiresAt); if err != nil || !maximum.Equal(expires) { return errors.New("lease maximum expiry must match its 60-second authority window") }; return nil
}

func ValidateRenewedLeaseTiming(lease ExecutorLease) error {
	claimed, err := time.Parse(time.RFC3339, lease.ClaimedAt); if err != nil { return errors.New("invalid lease claim time") }; renew, err := time.Parse(time.RFC3339, lease.RenewAfter); if err != nil || !renew.After(claimed) { return errors.New("renewed lease check-in must advance") }; expires, err := time.Parse(time.RFC3339, lease.LeaseExpiresAt); if err != nil || !expires.Equal(claimed.Add(time.Duration(ExecutorLeaseSeconds)*time.Second)) || renew.After(expires) { return errors.New("renewed lease must stay inside its 60-second authority") }; maximum, err := time.Parse(time.RFC3339, lease.MaximumExpiresAt); if err != nil || !maximum.Equal(expires) { return errors.New("lease maximum expiry must remain unchanged") }; return nil
}

func ValidateExecutorLeaseBinding(plan Plan, run Run, lease ExecutorLease) error {
	if plan.PlanID != run.PlanID || plan.PlanID != lease.PlanID || plan.PlanDigest != run.PlanDigest || plan.PlanDigest != lease.PlanDigest || plan.Binding.RecoveryEpoch != run.RecoveryEpoch || plan.Binding.RecoveryEpoch != lease.RecoveryEpoch || plan.Binding.StateRevision != run.StateRevision || run.RunID != lease.RunID || plan.ExecutorMode != run.ExecutorMode || run.ExecutorID != lease.ExecutorID || run.ExecutorBindingDigest != lease.BindingDigest { return errors.New("executor lease widens or changes its plan/run binding") }
	if plan.ExecutorMode == "external" && (plan.ExecutorID == nil || *plan.ExecutorID != run.ExecutorID) { return errors.New("external executor lease does not match plan executor") }
	stepMatches := 0
	var step RunStep
	for _, candidate := range run.Steps { if candidate.StepID == lease.StepID { stepMatches++; step = candidate } }
	if stepMatches != 1 { return errors.New("executor lease must name exactly one run step") }
	operationMatches := 0
	for _, operation := range plan.Operations {
		if operation.OperationID != lease.OperationID { continue }
		operationMatches++
		if operation.Sequence != step.Sequence || operation.OperationID != step.OperationID || operation.OperationType != step.OperationType || operation.ExecutorID != step.ExecutorID || operation.AdapterID != step.AdapterID || operation.TargetID != step.TargetID || operation.InputDigest != step.InputDigest || operation.ArtifactDigest != step.ArtifactDigest || operation.Idempotent != step.Idempotent { return errors.New("run step widens or changes its plan operation") }
		if step.ExecutorID != lease.ExecutorID || step.AdapterID != lease.AdapterID || step.TargetID != lease.TargetID || step.ArtifactDigest != lease.ArtifactDigest { return errors.New("executor lease widens or changes its run step") }
	}
	if operationMatches != 1 { return errors.New("executor lease operation must name exactly one plan operation") }
	return nil
}

func ValidateExecutionReceiptBinding(lease ExecutorLease, receipt ExecutionReceipt) error {
	if lease.LeaseID != receipt.LeaseID || lease.PlanID != receipt.PlanID || lease.PlanDigest != receipt.PlanDigest || lease.RunID != receipt.RunID || lease.StepID != receipt.StepID || lease.OperationID != receipt.OperationID || lease.ExecutorID != receipt.ExecutorID || lease.AdapterID != receipt.AdapterID || lease.TargetID != receipt.TargetID || lease.ArtifactDigest != receipt.ArtifactDigest || lease.BindingDigest != receipt.BindingDigest || lease.NonceDigest != receipt.NonceDigest || lease.RecoveryEpoch != receipt.RecoveryEpoch { return errors.New("execution receipt widens or changes its lease binding") }
	return nil
}
`)
	formatted, err := format.Source(output.Bytes())
	if err != nil {
		return nil, artifactError("GENERATED_GO_INVALID", "internal/generated/contracts_validate_gen.go:"+strconv.Itoa(len(output.Bytes())))
	}
	return formatted, nil
}
