package metadata

func accessProbeSchemas() []SchemaDefinition {
	return []SchemaDefinition{
		phase5Schema("vegastack-labs.dev/access-destination-observation", phase5ID("hostId", "HostID"), phase5Digest("identityDigest", "IdentityDigest"), phase5ID("contextId", "ContextID"), phase5Digest("contextDigest", "ContextDigest"), discoveryText("containerId", "ContainerID", 64), discoveryText("networkId", "NetworkID", 64), discoveryText("address", "Address", 64), phase5Digest("namespaceDigest", "NamespaceDigest"), phase5Positive("processId", "ProcessID"), discoveryText("processStart", "ProcessStart", 64), phase5Timestamp("observedAt", "ObservedAt")),
		phase5Schema("vegastack-labs.dev/access-probe-source", phase5ID("hostId", "HostID"), phase5Digest("identityDigest", "IdentityDigest"), phase5Enum("kind", "Kind", "host-network", "network-namespace", "container"), phase5ID("contextId", "ContextID"), phase5Digest("contextDigest", "ContextDigest"), phase5ID("interface", "Interface"), phase5Positive("interfaceIndex", "InterfaceIndex"), discoveryText("address", "Address", 64), phase5Enum("family", "Family", "ipv4", "ipv6"), phase5Digest("routeDigest", "RouteDigest")),
		phase5Schema("vegastack-labs.dev/access-probe-tuple", FieldDefinition{JSONName: "ownershipDigest", GoName: "OwnershipDigest", Kind: ValueString, OmitEmpty: true, Pattern: `^sha256:[a-f0-9]{64}$`}, phase5ID("hostId", "HostID"), phase5Digest("identityDigest", "IdentityDigest"), discoveryText("address", "Address", 64), phase5Positive("port", "Port"), phase5Enum("protocol", "Protocol", "tcp", "udp")),
		phase5Schema("vegastack-labs.dev/access-probe-case", phase5ID("probeId", "ProbeID"), phase5Enum("kind", "Kind", "ssh-admin", "ssh-wrong-user", "ssh-password", "ssh-root", "ssh-source", "host-flow", "container-published", "container-unpublished", "container-east-west"), phase5Enum("expected", "Expected", "allowed", "denied"), accessRef("destination", "Destination", "access-probe-tuple"), accessRef("witness", "Witness", "access-probe-tuple")),
		phase5Schema(accessProbeID, phase5ID("subjectHostId", "SubjectHostID"), phase5Digest("subjectIdentityDigest", "SubjectIdentityDigest"), discoveryText("subjectHostKey", "SubjectHostKey", 2048), phase5Digest("profileLockDigest", "ProfileLockDigest"), phase5Digest("applyInputDigest", "ApplyInputDigest"), phase5Digest("rollbackDigest", "RollbackDigest"), phase5ID("administratorUser", "AdministratorUser"), accessRef("source", "Source", "access-probe-source"), accessList("cases", "Cases", "vegastack-labs.dev/access-probe-case", 8), FieldDefinition{JSONName: "timeoutMillis", GoName: "TimeoutMillis", Kind: ValueInteger, Required: true, Minimum: int64Pointer(1), Maximum: int64Pointer(2000)}, FieldDefinition{JSONName: "attempts", GoName: "Attempts", Kind: ValueInteger, Required: true, Minimum: int64Pointer(1), Maximum: int64Pointer(2)}),
		phase5Schema(accessMeasurementID, FieldDefinition{JSONName: "baseline", GoName: "Baseline", Kind: ValueObject, Nullable: true, OmitEmpty: true, Ref: "vegastack-labs.dev/baseline-observation"}, FieldDefinition{JSONName: "volume", GoName: "Volume", Kind: ValueObject, Nullable: true, OmitEmpty: true, Ref: "vegastack-labs.dev/volume-observation"}, FieldDefinition{JSONName: "destinationOwnership", GoName: "DestinationOwnership", Kind: ValueArray, OmitEmpty: true, ItemRef: "vegastack-labs.dev/access-destination-observation", MaxItems: intPointer(8)}, phase5ID("controlId", "ControlID"), phase5Enum("kind", "Kind", "identity", "account", "ssh", "host-flow", "container-flow", "baseline", "volume"), phase5Enum("status", "Status", "passed", "failed", "partial", "unsupported", "error"), phase5ID("subjectHostId", "SubjectHostID"), phase5Digest("subjectIdentityDigest", "SubjectIdentityDigest"), phase5Digest("profileLockDigest", "ProfileLockDigest"), phase5ID("producerId", "ProducerID"), phase5Version("producerVersion", "ProducerVersion"), phase5Digest("bundleDigest", "BundleDigest"), phase5Timestamp("observedAt", "ObservedAt"), phase5Digest("configurationDigest", "ConfigurationDigest"), phase5Digest("measurementDigest", "MeasurementDigest"), phase5Digest("positiveProbeDigest", "PositiveProbeDigest"), phase5Digest("negativeProbeDigest", "NegativeProbeDigest"), phase5ID("reason", "Reason"), FieldDefinition{JSONName: "probe", GoName: "Probe", Kind: ValueObject, Nullable: true, OmitEmpty: true, Ref: "vegastack-labs.dev/access-probe-observation"}, FieldDefinition{JSONName: "rollbackRecordDigest", GoName: "RollbackRecordDigest", Kind: ValueString, OmitEmpty: true, Pattern: `^sha256:[a-f0-9]{64}$`}),
		phase5Schema("vegastack-labs.dev/access-probe-observation", phase5ID("probeId", "ProbeID"), phase5ID("sourceHostId", "SourceHostID"), phase5Digest("sourceIdentityDigest", "SourceIdentityDigest"), phase5Digest("sourceContextDigest", "SourceContextDigest"), discoveryText("actualSourceAddress", "ActualSourceAddress", 64), phase5Digest("sourceNamespaceDigest", "SourceNamespaceDigest"), phase5Digest("destinationDigest", "DestinationDigest"), phase5Digest("witnessDigest", "WitnessDigest"), phase5Enum("expected", "Expected", "allowed", "denied"), phase5Enum("actual", "Actual", "allowed", "denied", "error")),
		phase5Schema("vegastack-labs.dev/host-control-result", phase5ID("hostId", "HostID"), phase5Digest("identityDigest", "IdentityDigest"), phase5Enum("identityClass", "IdentityClass", "physical", "qualified-virtual"), phase5ID("profileId", "ProfileID"), phase5ID("osFamily", "OSFamily"), discoveryText("osVersion", "OSVersion", 64), FieldDefinition{JSONName: "osBuild", GoName: "OSBuild", Kind: ValueString, Required: true, Nullable: true, MaxLength: intPointer(128)}, phase5ID("architecture", "Architecture"), phase5ID("roleId", "RoleID"), phase5Version("baselineVersion", "BaselineVersion"), phase5ID("controlId", "ControlID"), phase5ID("producerId", "ProducerID"), phase5Version("producerVersion", "ProducerVersion"), phase5Digest("actionReceiptDigest", "ActionReceiptDigest"), phase5ID("declarationId", "DeclarationID"), phase5Positive("declarationRevision", "DeclarationRevision"), phase5Nonnegative("recoveryEpoch", "RecoveryEpoch"), phase5Timestamp("observedAt", "ObservedAt"), phase5Enum("status", "Status", "passed", "failed", "partial", "unsupported", "error"), phase5Digest("measurementDigest", "MeasurementDigest"), phase5Digest("positiveProbeDigest", "PositiveProbeDigest"), phase5Digest("negativeProbeDigest", "NegativeProbeDigest"), FieldDefinition{JSONName: "qualificationDigest", GoName: "QualificationDigest", Kind: ValueString, Required: true, Nullable: true, Pattern: `^sha256:[a-f0-9]{64}$`}),
	}
}
