package metadata

const baselineInputID = "vegastack-labs.dev/debian-baseline-input"
const baselineScopeID = "vegastack-labs.dev/host-baseline-scope"

func baselineOptionalDigest(j, g string) FieldDefinition {
	return FieldDefinition{JSONName: j, GoName: g, Kind: ValueString, OmitEmpty: true, Pattern: `^sha256:[a-f0-9]{64}$`}
}
func baselineSchemas() []SchemaDefinition {
	base := []FieldDefinition{phase5ID("hostId", "HostID"), phase5Digest("hostIdentityDigest", "HostIdentityDigest"), phase5ID("profileId", "ProfileID"), phase5Digest("profileLockDigest", "ProfileLockDigest"), accessRef("profileLock", "ProfileLock", "debian-profile-lock"), phase5Enum("roleId", "RoleID", "control", "application", "ci", "host", "recovery-spare", "reserve"), phase5Version("actionVersion", "ActionVersion"), phase5Positive("automationUid", "AutomationUID")}
	in := append([]FieldDefinition{}, base...)
	in = append(in, phase5Digest("renderedPolicyDigest", "RenderedPolicyDigest"), accessStrings("controlIds", "ControlIDs", 8), accessStrings("recoverySourcePrefixes", "RecoverySourcePrefixes", 32), phase5Enum("updateOwner", "UpdateOwner", "unattended-upgrades", "apt-periodic", "operator"), phase5Enum("timeOwner", "TimeOwner", "systemd-timesyncd", "chrony"), accessStrings("auditPaths", "AuditPaths", 32), accessList("appArmorProfiles", "AppArmorProfiles", "vegastack-labs.dev/baseline-apparmor-profile", 16), accessRef("aide", "AIDE", "baseline-aide-policy"), accessList("resources", "Resources", "vegastack-labs.dev/baseline-resource-limit", 16), accessList("kernelSettings", "KernelSettings", "vegastack-labs.dev/baseline-kernel-setting", 16), accessList("volumes", "Volumes", "vegastack-labs.dev/host-volume-binding", 16))
	recovery := append([]FieldDefinition{}, base...)
	recovery = append(recovery, accessRef("binding", "Binding", "host-volume-binding"), phase5Digest("priorVolumeReceiptDigest", "PriorVolumeReceiptDigest"), phase5ID("recoveryReferenceId", "RecoveryReferenceID"), phase5ID("recoveryMaterialVersion", "RecoveryMaterialVersion"))
	return []SchemaDefinition{
		phase5Schema(baselineInputID, in...),
		phase5Schema("vegastack-labs.dev/volume-recovery-input", recovery...),
		phase5Schema("vegastack-labs.dev/baseline-apparmor-profile", phase5ID("profileId", "ProfileID"), phase5ID("packageName", "PackageName"), phase5Digest("profileDigest", "ProfileDigest"), phase5ID("allowedProbeSelector", "AllowedProbeSelector"), phase5ID("deniedProbeSelector", "DeniedProbeSelector")),
		phase5Schema("vegastack-labs.dev/baseline-aide-policy", accessStrings("scopePaths", "ScopePaths", 32), phase5Digest("scopeDigest", "ScopeDigest"), baselineOptionalDigest("previousDigest", "PreviousDigest"), baselineOptionalDigest("approvedChangeDigest", "ApprovedChangeDigest"), baselineOptionalDigest("referenceDigest", "ReferenceDigest")),
		phase5Schema("vegastack-labs.dev/baseline-resource-limit", phase5ID("unit", "Unit"), discoveryText("mountPath", "MountPath", 256), phase5Positive("memoryMaxBytes", "MemoryMaxBytes"), phase5Positive("tasksMax", "TasksMax"), phase5Positive("cpuQuotaPercent", "CPUQuotaPercent"), phase5Positive("minimumFreeBytes", "MinimumFreeBytes"), phase5Positive("minimumFreePercent", "MinimumFreePercent")),
		phase5Schema("vegastack-labs.dev/baseline-kernel-setting", phase5Enum("name", "Name", "kernel.dmesg_restrict", "kernel.kptr_restrict", "kernel.yama.ptrace_scope", "fs.protected_hardlinks", "fs.protected_symlinks"), phase5Enum("value", "Value", "1", "2")),
		phase5Schema("vegastack-labs.dev/host-volume-binding", phase5ID("hostId", "HostID"), phase5Digest("hostIdentityDigest", "HostIdentityDigest"), phase5ID("volumeId", "VolumeID"), phase5ID("controlHostId", "ControlHostID"), phase5Digest("controlHostIdentityDigest", "ControlHostIdentityDigest"), phase5Positive("headerBytes", "HeaderBytes"), discoveryText("luksUuid", "LUKSUUID", 64), phase5Digest("headerDigest", "HeaderDigest"), phase5Digest("mappingDigest", "MappingDigest"), phase5Digest("mountBindingDigest", "MountBindingDigest"), phase5ID("mapperName", "MapperName"), discoveryText("mountPath", "MountPath", 256), phase5Nonnegative("deviceMajor", "DeviceMajor"), phase5Nonnegative("deviceMinor", "DeviceMinor"), FieldDefinition{JSONName: "keySlot", GoName: "KeySlot", Kind: ValueInteger, Required: true, Minimum: int64Pointer(0), Maximum: int64Pointer(31)}, phase5ID("recoveryCustodianId", "RecoveryCustodianID"), phase5Digest("recoveryCustodianIdentityDigest", "RecoveryCustodianIdentityDigest"), phase5Digest("recoveryTargetDigest", "RecoveryTargetDigest"), phase5Digest("recoveryReferenceDigest", "RecoveryReferenceDigest"), phase5ID("declarationId", "DeclarationID"), phase5Positive("declarationRevision", "DeclarationRevision"), phase5Nonnegative("recoveryEpoch", "RecoveryEpoch")),
		phase5Schema(baselineScopeID, phase5ID("subjectHostId", "SubjectHostID"), phase5Digest("subjectIdentityDigest", "SubjectIdentityDigest"), phase5ID("executionHostId", "ExecutionHostID"), phase5Digest("executionIdentityDigest", "ExecutionIdentityDigest"), phase5ID("profileId", "ProfileID"), phase5Digest("profileLockDigest", "ProfileLockDigest"), phase5ID("roleId", "RoleID"), accessStrings("controlIds", "ControlIDs", 8), baselineOptionalDigest("priorVolumeReceiptDigest", "PriorVolumeReceiptDigest")),
		phase5Schema("vegastack-labs.dev/baseline-observation", phase5Digest("factsDigest", "FactsDigest"), phase5Enum("verification", "Verification", "configuration-observed", "effective-probe", "unavailable"), baselineOptionalDigest("nativeQualificationDigest", "NativeQualificationDigest"), baselineOptionalDigest("aideReferenceDigest", "AIDEReferenceDigest")),
		phase5Schema("vegastack-labs.dev/volume-observation", accessRef("binding", "Binding", "host-volume-binding"), phase5Enum("kind", "Kind", "mapping", "recovery"), phase5Digest("factsDigest", "FactsDigest"), baselineOptionalDigest("priorVolumeReceiptDigest", "PriorVolumeReceiptDigest"), phase5Timestamp("observedAt", "ObservedAt")),
	}
}
